export const WORLD_COUNTRIES = [
  ["AD", "อันดอร์รา", "Andorra", "Europe/Andorra"],
  ["AE", "สหรัฐอาหรับเอมิเรตส์", "United Arab Emirates", "Asia/Dubai"],
  ["AF", "อัฟกานิสถาน", "Afghanistan", "Asia/Kabul"],
  ["AG", "แอนติกาและบาร์บูดา", "Antigua & Barbuda", "America/Antigua"],
  ["AI", "แองกวิลลา", "Anguilla", "America/Anguilla"],
  ["AL", "แอลเบเนีย", "Albania", "Europe/Tirane"],
  ["AM", "อาร์เมเนีย", "Armenia", "Asia/Yerevan"],
  ["AO", "แองโกลา", "Angola", "Africa/Luanda"],
  ["AQ", "แอนตาร์กติกา", "Antarctica", "Antarctica/McMurdo"],
  ["AR", "อาร์เจนตินา", "Argentina", "America/Argentina/Buenos_Aires"],
  ["AS", "อเมริกันซามัว", "American Samoa", "Pacific/Pago_Pago"],
  ["AT", "ออสเตรีย", "Austria", "Europe/Vienna"],
  ["AU", "ออสเตรเลีย", "Australia", "Australia/Sydney"],
  ["AW", "อารูบา", "Aruba", "America/Aruba"],
  ["AX", "หมู่เกาะโอลันด์", "Åland Islands", "Europe/Mariehamn"],
  ["AZ", "อาเซอร์ไบจาน", "Azerbaijan", "Asia/Baku"],
  ["BA", "บอสเนียและเฮอร์เซโกวีนา", "Bosnia & Herzegovina", "Europe/Sarajevo"],
  ["BB", "บาร์เบโดส", "Barbados", "America/Barbados"],
  ["BD", "บังกลาเทศ", "Bangladesh", "Asia/Dhaka"],
  ["BE", "เบลเยียม", "Belgium", "Europe/Brussels"],
  ["BF", "บูร์กินาฟาโซ", "Burkina Faso", "Africa/Ouagadougou"],
  ["BG", "บัลแกเรีย", "Bulgaria", "Europe/Sofia"],
  ["BH", "บาห์เรน", "Bahrain", "Asia/Bahrain"],
  ["BI", "บุรุนดี", "Burundi", "Africa/Bujumbura"],
  ["BJ", "เบนิน", "Benin", "Africa/Porto-Novo"],
  ["BL", "เซนต์บาร์เธเลมี", "St. Barthélemy", "America/St_Barthelemy"],
  ["BM", "เบอร์มิวดา", "Bermuda", "Atlantic/Bermuda"],
  ["BN", "บรูไน", "Brunei", "Asia/Brunei"],
  ["BO", "โบลิเวีย", "Bolivia", "America/La_Paz"],
  ["BQ", "เนเธอร์แลนด์แคริบเบียน", "Caribbean Netherlands", "America/Kralendijk"],
  ["BR", "บราซิล", "Brazil", "America/Sao_Paulo"],
  ["BS", "บาฮามาส", "Bahamas", "America/Nassau"],
  ["BT", "ภูฏาน", "Bhutan", "Asia/Thimphu"],
  ["BV", "เกาะบูเว", "Bouvet Island", "Etc/UTC"],
  ["BW", "บอตสวานา", "Botswana", "Africa/Gaborone"],
  ["BY", "เบลารุส", "Belarus", "Europe/Minsk"],
  ["BZ", "เบลีซ", "Belize", "America/Belize"],
  ["CA", "แคนาดา", "Canada", "America/Toronto"],
  ["CC", "หมู่เกาะโคโคส (คีลิง)", "Cocos (Keeling) Islands", "Indian/Cocos"],
  ["CD", "คองโก - กินชาซา", "Congo - Kinshasa", "Africa/Kinshasa"],
  ["CF", "สาธารณรัฐแอฟริกากลาง", "Central African Republic", "Africa/Bangui"],
  ["CG", "คองโก - บราซซาวิล", "Congo - Brazzaville", "Africa/Brazzaville"],
  ["CH", "สวิตเซอร์แลนด์", "Switzerland", "Europe/Zurich"],
  ["CI", "โกตดิวัวร์", "Côte d’Ivoire", "Africa/Abidjan"],
  ["CK", "หมู่เกาะคุก", "Cook Islands", "Pacific/Rarotonga"],
  ["CL", "ชิลี", "Chile", "America/Santiago"],
  ["CM", "แคเมอรูน", "Cameroon", "Africa/Douala"],
  ["CN", "จีน", "China", "Asia/Shanghai"],
  ["CO", "โคลอมเบีย", "Colombia", "America/Bogota"],
  ["CR", "คอสตาริกา", "Costa Rica", "America/Costa_Rica"],
  ["CU", "คิวบา", "Cuba", "America/Havana"],
  ["CV", "เคปเวิร์ด", "Cape Verde", "Atlantic/Cape_Verde"],
  ["CW", "คูราเซา", "Curaçao", "America/Curacao"],
  ["CX", "เกาะคริสต์มาส", "Christmas Island", "Indian/Christmas"],
  ["CY", "ไซปรัส", "Cyprus", "Asia/Nicosia"],
  ["CZ", "เช็ก", "Czechia", "Europe/Prague"],
  ["DE", "เยอรมนี", "Germany", "Europe/Berlin"],
  ["DJ", "จิบูตี", "Djibouti", "Africa/Djibouti"],
  ["DK", "เดนมาร์ก", "Denmark", "Europe/Copenhagen"],
  ["DM", "โดมินิกา", "Dominica", "America/Dominica"],
  ["DO", "สาธารณรัฐโดมินิกัน", "Dominican Republic", "America/Santo_Domingo"],
  ["DZ", "แอลจีเรีย", "Algeria", "Africa/Algiers"],
  ["EC", "เอกวาดอร์", "Ecuador", "America/Guayaquil"],
  ["EE", "เอสโตเนีย", "Estonia", "Europe/Tallinn"],
  ["EG", "อียิปต์", "Egypt", "Africa/Cairo"],
  ["EH", "ซาฮาราตะวันตก", "Western Sahara", "Africa/El_Aaiun"],
  ["ER", "เอริเทรีย", "Eritrea", "Africa/Asmara"],
  ["ES", "สเปน", "Spain", "Europe/Madrid"],
  ["ET", "เอธิโอเปีย", "Ethiopia", "Africa/Addis_Ababa"],
  ["FI", "ฟินแลนด์", "Finland", "Europe/Helsinki"],
  ["FJ", "ฟิจิ", "Fiji", "Pacific/Fiji"],
  ["FK", "หมู่เกาะฟอล์กแลนด์", "Falkland Islands", "Atlantic/Stanley"],
  ["FM", "ไมโครนีเซีย", "Micronesia", "Pacific/Pohnpei"],
  ["FO", "หมู่เกาะแฟโร", "Faroe Islands", "Atlantic/Faroe"],
  ["FR", "ฝรั่งเศส", "France", "Europe/Paris"],
  ["GA", "กาบอง", "Gabon", "Africa/Libreville"],
  ["GB", "สหราชอาณาจักร", "United Kingdom", "Europe/London"],
  ["GD", "เกรเนดา", "Grenada", "America/Grenada"],
  ["GE", "จอร์เจีย", "Georgia", "Asia/Tbilisi"],
  ["GF", "เฟรนช์เกียนา", "French Guiana", "America/Cayenne"],
  ["GG", "เกิร์นซีย์", "Guernsey", "Europe/Guernsey"],
  ["GH", "กานา", "Ghana", "Africa/Accra"],
  ["GI", "ยิบรอลตาร์", "Gibraltar", "Europe/Gibraltar"],
  ["GL", "กรีนแลนด์", "Greenland", "America/Nuuk"],
  ["GM", "แกมเบีย", "Gambia", "Africa/Banjul"],
  ["GN", "กินี", "Guinea", "Africa/Conakry"],
  ["GP", "กวาเดอลูป", "Guadeloupe", "America/Guadeloupe"],
  ["GQ", "อิเควทอเรียลกินี", "Equatorial Guinea", "Africa/Malabo"],
  ["GR", "กรีซ", "Greece", "Europe/Athens"],
  ["GS", "เกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช", "South Georgia & South Sandwich Islands", "Atlantic/South_Georgia"],
  ["GT", "กัวเตมาลา", "Guatemala", "America/Guatemala"],
  ["GU", "กวม", "Guam", "Pacific/Guam"],
  ["GW", "กินี-บิสเซา", "Guinea-Bissau", "Africa/Bissau"],
  ["GY", "กายอานา", "Guyana", "America/Guyana"],
  ["HK", "เขตปกครองพิเศษฮ่องกงแห่งสาธารณรัฐประชาชนจีน", "Hong Kong SAR China", "Asia/Hong_Kong"],
  ["HM", "เกาะเฮิร์ดและหมู่เกาะแมกดอนัลด์", "Heard & McDonald Islands", "Etc/UTC"],
  ["HN", "ฮอนดูรัส", "Honduras", "America/Tegucigalpa"],
  ["HR", "โครเอเชีย", "Croatia", "Europe/Zagreb"],
  ["HT", "เฮติ", "Haiti", "America/Port-au-Prince"],
  ["HU", "ฮังการี", "Hungary", "Europe/Budapest"],
  ["ID", "อินโดนีเซีย", "Indonesia", "Asia/Jakarta"],
  ["IE", "ไอร์แลนด์", "Ireland", "Europe/Dublin"],
  ["IL", "อิสราเอล", "Israel", "Asia/Jerusalem"],
  ["IM", "เกาะแมน", "Isle of Man", "Europe/Isle_of_Man"],
  ["IN", "อินเดีย", "India", "Asia/Kolkata"],
  ["IO", "บริติชอินเดียนโอเชียนเทร์ริทอรี", "British Indian Ocean Territory", "Indian/Chagos"],
  ["IQ", "อิรัก", "Iraq", "Asia/Baghdad"],
  ["IR", "อิหร่าน", "Iran", "Asia/Tehran"],
  ["IS", "ไอซ์แลนด์", "Iceland", "Atlantic/Reykjavik"],
  ["IT", "อิตาลี", "Italy", "Europe/Rome"],
  ["JE", "เจอร์ซีย์", "Jersey", "Europe/Jersey"],
  ["JM", "จาเมกา", "Jamaica", "America/Jamaica"],
  ["JO", "จอร์แดน", "Jordan", "Asia/Amman"],
  ["JP", "ญี่ปุ่น", "Japan", "Asia/Tokyo"],
  ["KE", "เคนยา", "Kenya", "Africa/Nairobi"],
  ["KG", "คีร์กีซสถาน", "Kyrgyzstan", "Asia/Bishkek"],
  ["KH", "กัมพูชา", "Cambodia", "Asia/Phnom_Penh"],
  ["KI", "คิริบาส", "Kiribati", "Pacific/Tarawa"],
  ["KM", "คอโมโรส", "Comoros", "Indian/Comoro"],
  ["KN", "เซนต์คิตส์และเนวิส", "St. Kitts & Nevis", "America/St_Kitts"],
  ["KP", "เกาหลีเหนือ", "North Korea", "Asia/Pyongyang"],
  ["KR", "เกาหลีใต้", "South Korea", "Asia/Seoul"],
  ["KW", "คูเวต", "Kuwait", "Asia/Kuwait"],
  ["KY", "หมู่เกาะเคย์แมน", "Cayman Islands", "America/Cayman"],
  ["KZ", "คาซัคสถาน", "Kazakhstan", "Asia/Almaty"],
  ["LA", "ลาว", "Laos", "Asia/Vientiane"],
  ["LB", "เลบานอน", "Lebanon", "Asia/Beirut"],
  ["LC", "เซนต์ลูเซีย", "St. Lucia", "America/St_Lucia"],
  ["LI", "ลิกเตนสไตน์", "Liechtenstein", "Europe/Vaduz"],
  ["LK", "ศรีลังกา", "Sri Lanka", "Asia/Colombo"],
  ["LR", "ไลบีเรีย", "Liberia", "Africa/Monrovia"],
  ["LS", "เลโซโท", "Lesotho", "Africa/Maseru"],
  ["LT", "ลิทัวเนีย", "Lithuania", "Europe/Vilnius"],
  ["LU", "ลักเซมเบิร์ก", "Luxembourg", "Europe/Luxembourg"],
  ["LV", "ลัตเวีย", "Latvia", "Europe/Riga"],
  ["LY", "ลิเบีย", "Libya", "Africa/Tripoli"],
  ["MA", "โมร็อกโก", "Morocco", "Africa/Casablanca"],
  ["MC", "โมนาโก", "Monaco", "Europe/Monaco"],
  ["MD", "มอลโดวา", "Moldova", "Europe/Chisinau"],
  ["ME", "มอนเตเนโกร", "Montenegro", "Europe/Podgorica"],
  ["MF", "เซนต์มาร์ติน", "St. Martin", "America/Marigot"],
  ["MG", "มาดากัสการ์", "Madagascar", "Indian/Antananarivo"],
  ["MH", "หมู่เกาะมาร์แชลล์", "Marshall Islands", "Pacific/Majuro"],
  ["MK", "มาซิโดเนียเหนือ", "North Macedonia", "Europe/Skopje"],
  ["ML", "มาลี", "Mali", "Africa/Bamako"],
  ["MM", "เมียนมา (พม่า)", "Myanmar (Burma)", "Asia/Yangon"],
  ["MN", "มองโกเลีย", "Mongolia", "Asia/Ulaanbaatar"],
  ["MO", "เขตปกครองพิเศษมาเก๊าแห่งสาธารณรัฐประชาชนจีน", "Macao SAR China", "Asia/Macau"],
  ["MP", "หมู่เกาะนอร์เทิร์นมาเรียนา", "Northern Mariana Islands", "Pacific/Saipan"],
  ["MQ", "มาร์ตินีก", "Martinique", "America/Martinique"],
  ["MR", "มอริเตเนีย", "Mauritania", "Africa/Nouakchott"],
  ["MS", "มอนต์เซอร์รัต", "Montserrat", "America/Montserrat"],
  ["MT", "มอลตา", "Malta", "Europe/Malta"],
  ["MU", "มอริเชียส", "Mauritius", "Indian/Mauritius"],
  ["MV", "มัลดีฟส์", "Maldives", "Indian/Maldives"],
  ["MW", "มาลาวี", "Malawi", "Africa/Blantyre"],
  ["MX", "เม็กซิโก", "Mexico", "America/Mexico_City"],
  ["MY", "มาเลเซีย", "Malaysia", "Asia/Kuala_Lumpur"],
  ["MZ", "โมซัมบิก", "Mozambique", "Africa/Maputo"],
  ["NA", "นามิเบีย", "Namibia", "Africa/Windhoek"],
  ["NC", "นิวแคลิโดเนีย", "New Caledonia", "Pacific/Noumea"],
  ["NE", "ไนเจอร์", "Niger", "Africa/Niamey"],
  ["NF", "เกาะนอร์ฟอล์ก", "Norfolk Island", "Pacific/Norfolk"],
  ["NG", "ไนจีเรีย", "Nigeria", "Africa/Lagos"],
  ["NI", "นิการากัว", "Nicaragua", "America/Managua"],
  ["NL", "เนเธอร์แลนด์", "Netherlands", "Europe/Amsterdam"],
  ["NO", "นอร์เวย์", "Norway", "Europe/Oslo"],
  ["NP", "เนปาล", "Nepal", "Asia/Kathmandu"],
  ["NR", "นาอูรู", "Nauru", "Pacific/Nauru"],
  ["NU", "นีอูเอ", "Niue", "Pacific/Niue"],
  ["NZ", "นิวซีแลนด์", "New Zealand", "Pacific/Auckland"],
  ["OM", "โอมาน", "Oman", "Asia/Muscat"],
  ["PA", "ปานามา", "Panama", "America/Panama"],
  ["PE", "เปรู", "Peru", "America/Lima"],
  ["PF", "เฟรนช์โปลินีเซีย", "French Polynesia", "Pacific/Tahiti"],
  ["PG", "ปาปัวนิวกินี", "Papua New Guinea", "Pacific/Port_Moresby"],
  ["PH", "ฟิลิปปินส์", "Philippines", "Asia/Manila"],
  ["PK", "ปากีสถาน", "Pakistan", "Asia/Karachi"],
  ["PL", "โปแลนด์", "Poland", "Europe/Warsaw"],
  ["PM", "แซงปีแยร์และมีเกอลง", "St. Pierre & Miquelon", "America/Miquelon"],
  ["PN", "หมู่เกาะพิตแคร์น", "Pitcairn Islands", "Pacific/Pitcairn"],
  ["PR", "เปอร์โตริโก", "Puerto Rico", "America/Puerto_Rico"],
  ["PS", "ดินแดนปาเลสไตน์", "Palestinian Territories", "Asia/Gaza"],
  ["PT", "โปรตุเกส", "Portugal", "Europe/Lisbon"],
  ["PW", "ปาเลา", "Palau", "Pacific/Palau"],
  ["PY", "ปารากวัย", "Paraguay", "America/Asuncion"],
  ["QA", "กาตาร์", "Qatar", "Asia/Qatar"],
  ["RE", "เรอูนียง", "Réunion", "Indian/Reunion"],
  ["RO", "โรมาเนีย", "Romania", "Europe/Bucharest"],
  ["RS", "เซอร์เบีย", "Serbia", "Europe/Belgrade"],
  ["RU", "รัสเซีย", "Russia", "Europe/Moscow"],
  ["RW", "รวันดา", "Rwanda", "Africa/Kigali"],
  ["SA", "ซาอุดีอาระเบีย", "Saudi Arabia", "Asia/Riyadh"],
  ["SB", "หมู่เกาะโซโลมอน", "Solomon Islands", "Pacific/Guadalcanal"],
  ["SC", "เซเชลส์", "Seychelles", "Indian/Mahe"],
  ["SD", "ซูดาน", "Sudan", "Africa/Khartoum"],
  ["SE", "สวีเดน", "Sweden", "Europe/Stockholm"],
  ["SG", "สิงคโปร์", "Singapore", "Asia/Singapore"],
  ["SH", "เซนต์เฮเลนา", "St. Helena", "Atlantic/St_Helena"],
  ["SI", "สโลวีเนีย", "Slovenia", "Europe/Ljubljana"],
  ["SJ", "สฟาลบาร์และยานไมเอน", "Svalbard & Jan Mayen", "Arctic/Longyearbyen"],
  ["SK", "สโลวะเกีย", "Slovakia", "Europe/Bratislava"],
  ["SL", "เซียร์ราลีโอน", "Sierra Leone", "Africa/Freetown"],
  ["SM", "ซานมาริโน", "San Marino", "Europe/San_Marino"],
  ["SN", "เซเนกัล", "Senegal", "Africa/Dakar"],
  ["SO", "โซมาเลีย", "Somalia", "Africa/Mogadishu"],
  ["SR", "ซูรินาเม", "Suriname", "America/Paramaribo"],
  ["SS", "ซูดานใต้", "South Sudan", "Africa/Juba"],
  ["ST", "เซาตูเมและปรินซิปี", "São Tomé & Príncipe", "Africa/Sao_Tome"],
  ["SV", "เอลซัลวาดอร์", "El Salvador", "America/El_Salvador"],
  ["SX", "ซินต์มาร์เทน", "Sint Maarten", "America/Lower_Princes"],
  ["SY", "ซีเรีย", "Syria", "Asia/Damascus"],
  ["SZ", "เอสวาตีนี", "Eswatini", "Africa/Mbabane"],
  ["TC", "หมู่เกาะเติกส์และหมู่เกาะเคคอส", "Turks & Caicos Islands", "America/Grand_Turk"],
  ["TD", "ชาด", "Chad", "Africa/Ndjamena"],
  ["TF", "เฟรนช์เซาเทิร์นเทร์ริทอรีส์", "French Southern Territories", "Indian/Kerguelen"],
  ["TG", "โตโก", "Togo", "Africa/Lome"],
  ["TH", "ไทย", "Thailand", "Asia/Bangkok"],
  ["TJ", "ทาจิกิสถาน", "Tajikistan", "Asia/Dushanbe"],
  ["TK", "โตเกเลา", "Tokelau", "Pacific/Fakaofo"],
  ["TL", "ติมอร์-เลสเต", "Timor-Leste", "Asia/Dili"],
  ["TM", "เติร์กเมนิสถาน", "Turkmenistan", "Asia/Ashgabat"],
  ["TN", "ตูนิเซีย", "Tunisia", "Africa/Tunis"],
  ["TO", "ตองกา", "Tonga", "Pacific/Tongatapu"],
  ["TR", "ตุรกี", "Türkiye", "Europe/Istanbul"],
  ["TT", "ตรินิแดดและโตเบโก", "Trinidad & Tobago", "America/Port_of_Spain"],
  ["TV", "ตูวาลู", "Tuvalu", "Pacific/Funafuti"],
  ["TW", "ไต้หวัน", "Taiwan", "Asia/Taipei"],
  ["TZ", "แทนซาเนีย", "Tanzania", "Africa/Dar_es_Salaam"],
  ["UA", "ยูเครน", "Ukraine", "Europe/Kyiv"],
  ["UG", "ยูกันดา", "Uganda", "Africa/Kampala"],
  ["UM", "หมู่เกาะรอบนอกของสหรัฐอเมริกา", "U.S. Outlying Islands", "Pacific/Midway"],
  ["US", "สหรัฐอเมริกา", "United States", "America/New_York"],
  ["UY", "อุรุกวัย", "Uruguay", "America/Montevideo"],
  ["UZ", "อุซเบกิสถาน", "Uzbekistan", "Asia/Samarkand"],
  ["VA", "นครวาติกัน", "Vatican City", "Europe/Vatican"],
  ["VC", "เซนต์วินเซนต์และเกรนาดีนส์", "St. Vincent & Grenadines", "America/St_Vincent"],
  ["VE", "เวเนซุเอลา", "Venezuela", "America/Caracas"],
  ["VG", "หมู่เกาะบริติชเวอร์จิน", "British Virgin Islands", "America/Tortola"],
  ["VI", "หมู่เกาะเวอร์จินของสหรัฐอเมริกา", "U.S. Virgin Islands", "America/St_Thomas"],
  ["VN", "เวียดนาม", "Vietnam", "Asia/Ho_Chi_Minh"],
  ["VU", "วานูอาตู", "Vanuatu", "Pacific/Efate"],
  ["WF", "วาลลิสและฟุตูนา", "Wallis & Futuna", "Pacific/Wallis"],
  ["WS", "ซามัว", "Samoa", "Pacific/Apia"],
  ["YE", "เยเมน", "Yemen", "Asia/Aden"],
  ["YT", "มายอต", "Mayotte", "Indian/Mayotte"],
  ["ZA", "แอฟริกาใต้", "South Africa", "Africa/Johannesburg"],
  ["ZM", "แซมเบีย", "Zambia", "Africa/Lusaka"],
  ["ZW", "ซิมบับเว", "Zimbabwe", "Africa/Harare"],
] as const;

