import { NextResponse } from "next/server";
import { z } from "zod";
import { getSession } from "@/src/lib/auth";
import { query } from "@/src/lib/db";
import { getTripRole } from "@/src/lib/trip-access";

const schema=z.object({tripId:z.string().uuid(),title:z.string().min(1),category:z.string(),expenseType:z.enum(["budget","actual"]),foreignAmount:z.number().nonnegative(),currency:z.string().length(3),exchangeRate:z.number().positive(),paymentMethod:z.string(),creditCardId:z.string().uuid().optional(),spentAt:z.string()});
export async function GET(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(session.isDemo)return NextResponse.json([]);const tripId=new URL(request.url).searchParams.get("tripId");if(!tripId)return NextResponse.json({error:"tripId is required"},{status:400});if(!await getTripRole(tripId,session.userId))return NextResponse.json({error:"Not found"},{status:404});const result=await query("SELECT e.* FROM expenses e WHERE e.trip_id=$1 ORDER BY e.spent_at DESC,e.created_at DESC",[tripId]);return NextResponse.json(result.rows);}
export async function POST(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(session.isDemo)return NextResponse.json({error:"Demo mode is read-only",loginRequired:true},{status:403});try{const x=schema.parse(await request.json());if(!await getTripRole(x.tripId,session.userId))return NextResponse.json({error:"Not found"},{status:404});const thb=Math.round(x.foreignAmount*x.exchangeRate*100)/100;const shopping=x.category.toLowerCase()==="shopping";const result=await query("INSERT INTO expenses (trip_id,title,category,expense_type,foreign_amount,currency,exchange_rate,amount_thb,payment_method,credit_card_id,is_shopping,spent_at,rate_stamped_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,now()) RETURNING *",[x.tripId,x.title,x.category,x.expenseType,x.foreignAmount,x.currency.toUpperCase(),x.exchangeRate,thb,x.paymentMethod,x.creditCardId??null,shopping,x.spentAt]);return NextResponse.json(result.rows[0],{status:201});}catch{return NextResponse.json({error:"Invalid expense data"},{status:400});}}
