import { boolean, date, integer, jsonb, numeric, pgEnum, pgTable, text, time, timestamp, uuid } from "drizzle-orm/pg-core";

export const timeSlot = pgEnum("time_slot", ["morning","afternoon","evening"]);
export const expenseType = pgEnum("expense_type", ["budget","actual"]);
export const users = pgTable("users", { id:uuid("id").defaultRandom().primaryKey(), sharedId:text("shared_id").notNull().unique(), displayName:text("display_name").notNull(), passwordHash:text("password_hash").notNull(), locale:text("locale").default("th").notNull(), theme:text("theme").default("system").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull() });
export const trips = pgTable("trips", { id:uuid("id").defaultRandom().primaryKey(), ownerId:uuid("owner_id").references(()=>users.id,{onDelete:"cascade"}).notNull(), name:text("name").notNull(), destination:text("destination").notNull(), startDate:date("start_date").notNull(), totalDays:integer("total_days").notNull(), travellerCount:integer("traveller_count").default(2).notNull(), budgetThb:numeric("budget_thb",{precision:14,scale:2}).default("0").notNull(), shoppingBudgetThb:numeric("shopping_budget_thb",{precision:14,scale:2}).default("0").notNull(), outboundDepartureAt:timestamp("outbound_departure_at"), returnDepartureAt:timestamp("return_departure_at"), coverImageUrl:text("cover_image_url"), googlePhotosUrl:text("google_photos_url") });
export const itineraries = pgTable("itineraries", { id:uuid("id").defaultRandom().primaryKey(), tripId:uuid("trip_id").references(()=>trips.id,{onDelete:"cascade"}).notNull(), dayNumber:integer("day_number").notNull(), timeSlot:timeSlot("time_slot").notNull(), startTime:time("start_time"), placeName:text("place_name"), address:text("address"), imageUrl:text("image_url"), transportMode:text("transport_mode"), transportNote:text("transport_note"), costItems:jsonb("cost_items").$type<Array<{key:string;value:number}>>().default([]).notNull(), sortOrder:integer("sort_order").default(0).notNull() });
export const creditCards = pgTable("credit_cards", { id:uuid("id").defaultRandom().primaryKey(), userId:uuid("user_id").references(()=>users.id,{onDelete:"cascade"}).notNull(), nickname:text("nickname").notNull(), brand:text("brand"), lastFour:text("last_four"), isActive:boolean("is_active").default(true).notNull() });
export const expenses = pgTable("expenses", { id:uuid("id").defaultRandom().primaryKey(), tripId:uuid("trip_id").references(()=>trips.id,{onDelete:"cascade"}).notNull(), title:text("title").notNull(), category:text("category").notNull(), expenseType:expenseType("expense_type").notNull(), foreignAmount:numeric("foreign_amount",{precision:14,scale:2}).notNull(), currency:text("currency").notNull(), exchangeRate:numeric("exchange_rate",{precision:14,scale:6}).notNull(), amountThb:numeric("amount_thb",{precision:14,scale:2}).notNull(), paymentMethod:text("payment_method").notNull(), creditCardId:uuid("credit_card_id").references(()=>creditCards.id,{onDelete:"set null"}), isShopping:boolean("is_shopping").default(false).notNull(), spentAt:date("spent_at").notNull(), rateStampedAt:timestamp("rate_stamped_at",{withTimezone:true}).defaultNow().notNull() });
export const lounges = pgTable("lounges", { id:uuid("id").defaultRandom().primaryKey(), tripId:uuid("trip_id").references(()=>trips.id,{onDelete:"cascade"}).notNull(), name:text("name").notNull(), airportCode:text("airport_code").notNull(), terminal:text("terminal"), accessMethod:text("access_method"), visitAt:timestamp("visit_at",{withTimezone:true}), notes:text("notes") });
