"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import {
  AlertTriangle, ArrowRight, CheckCircle2, ChevronRight, Coffee, Crown, Globe2, History, Hotel, ImagePlus,
  House, Languages, LogOut, MapPin, Moon, Navigation, Pencil, Plane,
  Plus, ReceiptText, Settings2, ShoppingBag, Sparkles, Sun, TrainFront,
  Trash2, UserRound, X,
} from "lucide-react";

type Screen = "dashboard" | "trip" | "timeline" | "expenses" | "settings";
type Lang = "TH" | "EN";
type Trip = { id:string; name:string; destination:string; start_date:string; total_days:number; budget_thb:string; shopping_budget_thb:string; outbound_departure_at:string|null; return_departure_at:string|null; cover_image_url:string|null };
type CostItem = { key:string; value:number };
type Itinerary = { id:string; day_number:number; time_slot:"morning"|"afternoon"|"evening"; start_time:string|null; place_name:string; address:string|null; image_url:string|null; transport_mode:string|null; transport_note:string|null; cost_items:CostItem[] };
type Expense = { id:string; title:string; category:string; expense_type:"budget"|"actual"; foreign_amount:string; currency:string; exchange_rate:string; amount_thb:string; payment_method:string; is_shopping:boolean; spent_at:string };
type Modal = { type:"trip"; trip?:Trip } | { type:"place"; item?:Itinerary } | { type:"expense" } | null;
type Confirmation = { title:string; description:string; confirmLabel?:string; onConfirm:()=>void|Promise<void> };

function Brand(){return <div className="brand"><Image src="/bn-trip-logo.png" alt="BN Trip" width={48} height={48} priority/><div>BN Trip<small>our tiny trip club</small></div></div>}

function EmptyState({title,description,action,onClick,icon:Icon=Navigation}:{title:string;description:string;action:string;onClick:()=>void;icon?:typeof Navigation}){
  return <article className="card empty-state"><span className="empty-icon"><Icon size={25}/></span><h3>{title}</h3><p>{description}</p><button className="primary-btn" onClick={onClick}><Plus size={16}/>{action}</button></article>;
}

function localDate(value:string|null|undefined,fallback=""){return value?value.slice(0,10):fallback.slice(0,10)}
function localTime(value:string|null|undefined,fallback="09:00"){return value?.slice(11,16)||fallback}
function addDays(dateValue:string,days:number){const date=new Date(`${dateValue.slice(0,10)}T00:00:00`);date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)}
function flightLabel(value:string|null){if(!value)return "ยังไม่ระบุ";const [date,time=""] = value.split("T");return `${new Date(`${date}T00:00:00`).toLocaleDateString("th-TH",{day:"numeric",month:"short",year:"2-digit"})} · ${time.slice(0,5)}`}
function moneyFormat(value:string|number){const clean=String(value??"").replace(/,/g,"").replace(/[^\d.]/g,"");if(!clean)return "";const [whole,decimal]=clean.split(".");return `${Number(whole||0).toLocaleString("en-US")}${decimal!==undefined?`.`+decimal.slice(0,2):""}`}
function MoneyInput({name,defaultValue,required=false}:{name:string;defaultValue?:string|number;required?:boolean}){const [value,setValue]=useState(()=>moneyFormat(defaultValue??""));return <input name={name} inputMode="decimal" value={value} required={required} onChange={e=>setValue(moneyFormat(e.target.value))}/>}

function LoginScreen(){
  const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget);try{const res=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sharedId:form.get("sharedId"),password:form.get("password")})});const json=await res.json();if(!res.ok)throw new Error(json.error);location.reload()}catch(err){setError(err instanceof Error?err.message:"เข้าสู่ระบบไม่สำเร็จ");setLoading(false)}}
  return <main className="login-page"><section className="login-art"><div className="eyebrow"><Sparkles size={13}/> private journeys · made together</div><h1>เก็บทุกเส้นทาง<br/>ไว้ในที่เดียว</h1><p>แพลนที่เที่ยว จดโมเมนต์ และคุมงบ<br/>ในสมุดเดินทางของ B & N</p><div className="login-route"><span>BKK</span><div><Plane size={20}/></div><span>ANYWHERE</span></div></section><section className="login-panel"><Brand/><div className="login-copy"><span className="mini-kicker">WELCOME BACK</span><h2>เปิดสมุดเดินทาง</h2><p>ใช้ Shared Trip ID เดียวกันเพื่อเข้าถึงแพลนของเรา</p></div><form className="form-grid" onSubmit={login}><div className="field"><label>SHARED TRIP ID</label><input name="sharedId" defaultValue="BNTOGETHER" required/></div><div className="field"><label>รหัสผ่าน</label><input name="password" type="password" defaultValue="bntogether" required/></div>{error&&<p className="login-error">{error}</p>}<button className="primary-btn" disabled={loading}>{loading?"กำลังเปิดสมุดทริป…":"เข้าสู่สมุดเดินทาง"}<ArrowRight size={16}/></button></form><p className="login-hint"><Crown size={12}/>พื้นที่ส่วนตัวสำหรับสมาชิกที่ใช้ Shared ID นี้</p></section></main>;
}

function TripCard({trip,past,now,selectTrip,editTrip,deleteTrip}:{trip:Trip;past?:boolean;now:number;selectTrip:(t:Trip)=>void;editTrip:(t:Trip)=>void;deleteTrip:(t:Trip)=>void}){
  const coverStyle=trip.cover_image_url?{backgroundImage:`linear-gradient(180deg,rgba(7,25,19,.08),rgba(7,25,19,.55)),url("${trip.cover_image_url}")`}:undefined;
  const departure=trip.outbound_departure_at?new Date(trip.outbound_departure_at).getTime():null;
  const countdownLabel=departure===null?"ยังไม่กำหนดวัน":departure<=now?"กำลังเดินทาง":`อีก ${Math.ceil((departure-now)/86400000)} วัน`;
  return <article className={`trip-card ${past?"past":""}`}><div className="trip-cover" style={coverStyle}><span>{trip.cover_image_url?"":trip.destination.slice(0,1).toUpperCase()}</span>{past?<b className="past-badge">ที่ผ่านมาแล้ว</b>:<b className="countdown-badge">{countdownLabel}</b>}<div className="trip-actions"><button onClick={()=>editTrip(trip)} aria-label="แก้ไข"><Pencil size={15}/></button><button onClick={()=>deleteTrip(trip)} aria-label="ลบ"><Trash2 size={15}/></button></div></div><div className="trip-body"><span className="eyebrow trip-duration">ไป {flightLabel(trip.outbound_departure_at)} · กลับ {flightLabel(trip.return_departure_at)}</span><h3>{trip.name}</h3><p><MapPin size={12}/>{trip.destination}</p><div className="trip-meta"><span>{trip.total_days} วัน</span><span>฿{Number(trip.budget_thb).toLocaleString()}</span></div><button className="open-trip" onClick={()=>selectTrip(trip)}>{past?"เปิดดูความทรงจำ":"เลือกทริปนี้"}<ChevronRight size={16}/></button></div></article>;
}

function Dashboard({trips,selectTrip,createTrip,editTrip,deleteTrip}:{trips:Trip[];selectTrip:(t:Trip)=>void;createTrip:()=>void;editTrip:(t:Trip)=>void;deleteTrip:(t:Trip)=>void}){
  const [now]=useState(()=>Date.now());
  const upcoming=trips.filter(t=>!t.return_departure_at||new Date(t.return_departure_at).getTime()>=now);
  const past=trips.filter(t=>t.return_departure_at&&new Date(t.return_departure_at).getTime()<now);
  const cards=(items:Trip[],isPast=false)=><div className="trip-grid">{items.map(t=><TripCard key={t.id} trip={t} past={isPast} now={now} selectTrip={selectTrip} editTrip={editTrip} deleteTrip={deleteTrip}/>)}</div>;
  return <div className="screen"><section className="welcome"><div><span className="eyebrow"><Sparkles size={13}/> OUR TRAVEL JOURNAL</span><h1>เรื่องราวระหว่างทาง</h1><p>แพลนทริปใหม่ หรือกลับมาเปิดดูเส้นทางและความทรงจำเดิมได้ทุกเมื่อ</p></div><div className="welcome-actions"><button className="primary-btn" onClick={createTrip}><Plus size={17}/>สร้างทริปใหม่</button></div></section><div className="grid stats dashboard-stats"><article className="card stat-card"><div className="stat-top"><span>ทริปทั้งหมด</span><span className="stat-icon"><Globe2 size={17}/></span></div><div className="stat-value">{trips.length}<small>journeys</small></div></article><article className="card stat-card"><div className="stat-top"><span>เดินทางแล้ว</span><span className="stat-icon"><History size={17}/></span></div><div className="stat-value">{past.length}<small>memories</small></div></article></div><div className="section-head"><div><span className="section-kicker">UPCOMING JOURNEYS</span><h2>ทริปที่กำลังจะมาถึง</h2><p>{upcoming.length} ทริปที่รอเราอยู่</p></div></div>{upcoming.length?cards(upcoming):<EmptyState title="หน้ากระดาษนี้ยังว่าง" description="สร้างทริปใหม่ แล้วเริ่มเติมสถานที่ที่อยากไปกัน" action="สร้างทริปใหม่" onClick={createTrip}/>}<div className="section-head past-head"><div><span className="section-kicker pink">PAST JOURNEYS</span><h2>ทริปที่ผ่านมาแล้ว</h2><p>ย้อนกลับไปดูเส้นทางและความทรงจำเดิมได้เสมอ</p></div><span className="past-count">{past.length}</span></div>{past.length?cards(past,true):<article className="card past-empty">เมื่อจบทริปแล้ว เราจะเก็บการเดินทางไว้ตรงนี้ให้อัตโนมัติ</article>}</div>;
}

function TripHeader({trip,back}:{trip:Trip;back:()=>void}){
  const coverStyle=trip.cover_image_url?{backgroundImage:`linear-gradient(90deg,rgba(20,24,27,.78),rgba(20,24,27,.3)),url("${trip.cover_image_url}")`}:undefined;
  return <><button className="back-btn" onClick={back}>← ย้อนกลับ</button><div className={`trip-detail-head ${trip.cover_image_url?"has-cover":""}`} style={coverStyle}><div><span className="eyebrow">{trip.destination}</span><h1 className="page-title">{trip.name}</h1><p className="page-sub">บิน {flightLabel(trip.outbound_departure_at)} · กลับ {flightLabel(trip.return_departure_at)} · {trip.total_days} วัน</p></div></div></>;
}

function TripHub({trip,items,day,setDay,back,openExpenses,editTrip,addPlace,editPlace}:{trip:Trip;items:Itinerary[];day:number;setDay:(day:number)=>void;back:()=>void;openExpenses:()=>void;editTrip:()=>void;addPlace:(day:number)=>void;editPlace:(item:Itinerary)=>void}){
  useEffect(()=>setDay(1),[trip.id,setDay]);
  const baseDate=localDate(trip.outbound_departure_at,trip.start_date);
  const dayItems=items.filter(item=>item.day_number===day).sort((a,b)=>(a.start_time||"99:99").localeCompare(b.start_time||"99:99"));
  const slots={morning:"เช้า",afternoon:"บ่าย",evening:"เย็น"};
  return <div className="screen">
    <TripHeader trip={trip} back={back}/>
    <div className="trip-hub-actions"><button className="text-btn" onClick={editTrip}><Pencil size={14}/>แก้ไขข้อมูลทริป</button><button className="text-btn" onClick={openExpenses}><ReceiptText size={14}/>ค่าใช้จ่ายทั้งหมด</button></div>
    <div className="day-strip">{Array.from({length:trip.total_days},(_,index)=>index+1).map(number=>{const date=new Date(`${baseDate}T00:00:00`);date.setDate(date.getDate()+number-1);return <button key={number} className={`day-pill ${day===number?"active":""}`} onClick={()=>setDay(number)}><small>DAY</small><strong>{number}</strong><small>{date.toLocaleDateString("en",{weekday:"short"})}</small></button>})}</div>
    <div className="section-head timeline-heading"><div><h2>แผนวันที่ {day}</h2><p>{dayItems.length} สถานที่ · เรียงตามเวลาอัตโนมัติ</p></div><button className="add-btn" onClick={()=>addPlace(day)} aria-label={`เพิ่มรายการวันที่ ${day}`}><Plus size={20}/></button></div>
    {dayItems.length===0?<EmptyState title={`Day ${day} ยังว่างอยู่`} description="เพิ่มสถานที่และเวลา รายการใหม่จะถูกเรียงใน Timeline อัตโนมัติ" action="เพิ่มสถานที่" onClick={()=>addPlace(day)}/>:<div className="timeline editable-timeline">{dayItems.map((item,index)=>{
      const isLast=index===dayItems.length-1;
      const previous=index>0?dayItems[index-1]:null;
      const costs=Array.isArray(item.cost_items)?item.cost_items:[];
      const total=costs.reduce((sum,cost)=>sum+Number(cost.value||0),0);
      const origin=previous?.address||previous?.place_name||"";
      const destination=item.address||item.place_name;
      const mode=item.transport_mode?.includes("เดิน")?"walking":item.transport_mode?.includes("รถยนต์")||item.transport_mode?.includes("แท็กซี่")?"driving":"transit";
      const mapsUrl=previous?`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&travelmode=${mode}`:"";
      return <div className={`timeline-stop ${isLast?"destination":""}`} key={item.id}>
        <div className="event"><div className="event-dot"><MapPin size={16}/></div><article className="event-card editable-event-card"><button className="event-card-main" onClick={()=>editPlace(item)}><div className="event-image"/><div className="event-copy"><span className="event-time">{item.start_time?.slice(0,5)||"ไม่ระบุเวลา"} · {slots[item.time_slot]}</span><h3>{item.place_name}</h3><p><MapPin size={10}/>{item.address||"ยังไม่ได้ระบุสถานที่"}</p>{item.transport_note&&<p className="event-detail">{item.transport_note}</p>}{costs.length>0&&<div className="timeline-costs"><span>{costs.length} รายการราคา</span><strong>฿{total.toLocaleString()}</strong></div>}</div><span className="event-edit"><Pencil size={14}/></span></button>{previous&&<a className="navigate-point-btn" href={mapsUrl} target="_blank" rel="noreferrer" aria-label={`นำทางจาก ${previous.place_name} ไป ${item.place_name}`}><Navigation size={15}/><span>นำทางจากจุดก่อนหน้า</span><ArrowRight size={14}/></a>}</article></div>
        {!isLast?<div className="transport"><TrainFront size={12}/><span>{item.transport_mode||"เส้นทางไปจุดถัดไป"}{item.transport_note?` · ${item.transport_note}`:""}</span></div>:<div className="destination-label"><MapPin size={12}/>จุดหมายสุดท้ายของวันนี้</div>}
      </div>
    })}</div>}
  </div>;
}

function TimelineScreen({trip,items,day,setDay,addPlace,back}:{trip:Trip;items:Itinerary[];day:number;setDay:(n:number)=>void;addPlace:()=>void;back:()=>void}){
  useEffect(()=>setDay(1),[trip.id,setDay]);
  const dayItems=items.filter(i=>i.day_number===day);
  const slots={morning:"เช้า",afternoon:"บ่าย",evening:"เย็น"};
  const baseDate=localDate(trip.outbound_departure_at,trip.start_date);
  return <div className="screen"><TripHeader trip={trip} back={back}/><div className="day-strip">{Array.from({length:trip.total_days},(_,i)=>i+1).map(n=>{const date=new Date(`${baseDate}T00:00:00`);date.setDate(date.getDate()+n-1);return <button key={n} className={`day-pill ${day===n?"active":""}`} onClick={()=>setDay(n)}><small>DAY</small><strong>{n}</strong><small>{date.toLocaleDateString("en",{weekday:"short"})}</small></button>})}</div><div className="section-head"><div><h2>แผนวันที่ {day}</h2><p>{dayItems.length} สถานที่</p></div><button className="add-btn" onClick={addPlace} aria-label="เพิ่มสถานที่"><Plus size={20}/></button></div>{dayItems.length===0?<EmptyState title={`Day ${day} ยังว่างอยู่`} description="เพิ่มสถานที่ เวลา และวิธีเดินทางสำหรับวันนี้" action="เพิ่มสถานที่" onClick={addPlace}/>:<div className="timeline">{dayItems.map((item,index)=><div key={item.id}><div className="event"><div className="event-dot"><MapPin size={16}/></div><article className="event-card"><div className="event-image"/><div className="event-copy"><span className="event-time">{item.start_time?.slice(0,5)||"ไม่ระบุเวลา"} · {slots[item.time_slot]}</span><h3>{item.place_name}</h3><p><MapPin size={10}/>{item.address||"ยังไม่ได้ระบุที่อยู่"}</p></div></article></div>{index<dayItems.length-1&&<div className="transport"><TrainFront size={12}/>{item.transport_mode||"เพิ่มวิธีเดินทาง"} {item.transport_note}</div>}</div>)}</div>}</div>;
}

function ExpensesScreen({trip,expenses,addExpense,back}:{trip:Trip;expenses:Expense[];addExpense:()=>void;back:()=>void}){
  const actual=expenses.filter(e=>e.expense_type==="actual"&&!e.is_shopping).reduce((s,e)=>s+Number(e.amount_thb),0);const shopping=expenses.filter(e=>e.is_shopping).reduce((s,e)=>s+Number(e.amount_thb),0);const budget=Number(trip.budget_thb);const percent=budget?Math.min(100,Math.round(actual/budget*100)):0;
  const iconFor=(category:string)=>category.toLowerCase()==="shopping"?ShoppingBag:category.includes("ที่พัก")?Hotel:category.includes("อาหาร")?Coffee:ReceiptText;
  return <div className="screen"><TripHeader trip={trip} back={back}/><div className="toolbar"><div><h2 style={{margin:0,fontWeight:500}}>ค่าใช้จ่ายของทริป</h2><p className="page-sub" style={{margin:0}}>ยอดเงินจริงพร้อมอัตราแลกเปลี่ยนที่ Stamp ไว้</p></div><button className="add-btn" onClick={addExpense}><Plus size={20}/></button></div><div className="grid stats"><article className="card stat-card"><div className="stat-top"><span>ใช้จ่ายหลัก</span><span>{percent}%</span></div><div><div className="stat-value">฿{actual.toLocaleString()} <small>/ ฿{budget.toLocaleString()}</small></div><div className="progress"><span style={{width:`${percent}%`}}/></div></div></article><article className="card stat-card shopping-card"><div className="stat-top"><span>Shopping · แยกงบ</span><ShoppingBag size={17}/></div><div className="stat-value">฿{shopping.toLocaleString()} <small>/ ฿{Number(trip.shopping_budget_thb).toLocaleString()}</small></div></article></div><div className="section-head"><div><h2>รายการค่าใช้จ่าย</h2><p>{expenses.length} รายการ</p></div></div>{expenses.length===0?<EmptyState title="ยังไม่มีค่าใช้จ่าย" description="เพิ่มงบหรือยอดจ่ายจริง ระบบจะเก็บสกุลเงินและอัตราแลกเปลี่ยนไว้ให้" action="เพิ่มค่าใช้จ่าย" onClick={addExpense} icon={ReceiptText}/>:<article className="card expense-list">{expenses.map(e=>{const Icon=iconFor(e.category);return <div className="expense-row" key={e.id}><span className="expense-cat"><Icon size={17}/></span><div><div className="expense-name">{e.title}</div><div className="expense-sub">{e.category} · {e.payment_method} · {e.expense_type}</div></div><div className="expense-amount">฿{Number(e.amount_thb).toLocaleString()}<small>{Number(e.foreign_amount).toLocaleString()} {e.currency} @ {e.exchange_rate}</small></div></div>})}</article>}</div>;
}

function SettingsScreen({dark,toggleTheme,lang,setLang,logout}:{dark:boolean;toggleTheme:()=>void;lang:Lang;setLang:(l:Lang)=>void;logout:()=>void}){
  return <div className="screen"><h1 className="page-title">ตั้งค่า</h1><p className="page-sub">ค่าของบัญชีและอุปกรณ์นี้</p><div className="settings-list"><article className="card"><div className="setting-row"><div className="setting-label"><span className="stat-icon">{dark?<Moon size={17}/>:<Sun size={17}/>}</span><div><strong>ธีมการแสดงผล</strong><small>สลับ Light / Dark mode</small></div></div><button className={`toggle ${dark?"on":""}`} onClick={toggleTheme} aria-label="เปลี่ยนธีม"><span/></button></div></article><article className="card"><div className="setting-row"><div className="setting-label"><span className="stat-icon"><Languages size={17}/></span><div><strong>ภาษา · Language</strong><small>ภาษาอินเทอร์เฟซหลัก</small></div></div><div className="segmented"><button className={lang==="TH"?"active":""} onClick={()=>setLang("TH")}>TH</button><button className={lang==="EN"?"active":""} onClick={()=>setLang("EN")}>EN</button></div></div></article><article className="card"><div className="setting-row"><div className="setting-label"><span className="stat-icon"><UserRound size={17}/></span><div><strong>Shared Trip ID</strong><small>BNTOGETHER · เชื่อมต่อบัญชีร่วมกัน</small></div></div><span style={{color:"var(--brand)",fontSize:11,fontWeight:600}}>ACTIVE</span></div></article><article className="card"><div className="section-head" style={{margin:0}}><div><h2>บัตรและการชำระเงิน</h2><p>ยังไม่มีบัตรที่บันทึกไว้</p></div><button className="text-btn">+ เพิ่มบัตร</button></div></article><article className="card logout-setting"><div className="setting-row"><div className="setting-label"><span className="stat-icon"><LogOut size={17}/></span><div><strong>ออกจากระบบ</strong><small>ออกจาก Shared account บนอุปกรณ์นี้</small></div></div><button className="settings-logout-btn" onClick={logout}>ออกจากระบบ</button></div></article></div></div>;
}

function ConfirmDialog({confirmation,close}:{confirmation:Confirmation;close:()=>void}){
  const [busy,setBusy]=useState(false);
  useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous}},[]);
  const confirm=async()=>{setBusy(true);try{await confirmation.onConfirm();close()}catch{setBusy(false)}};
  return <div className="confirm-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)close()}}><div className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><span className="confirm-icon"><AlertTriangle size={22}/></span><h2 id="confirm-title">{confirmation.title}</h2><p>{confirmation.description}</p><div className="confirm-actions"><button type="button" className="confirm-cancel" onClick={close} disabled={busy}>ยกเลิก</button><button type="button" className="confirm-delete" onClick={confirm} disabled={busy}>{busy?"กำลังลบ…":confirmation.confirmLabel||"ยืนยันการลบ"}</button></div></div></div>;
}

type CropSource = { file:File; image:HTMLImageElement; url:string };

function CoverImagePicker({existingUrl,onChange}:{existingUrl?:string|null;onChange:(file:File|null)=>void}){
  const inputRef=useRef<HTMLInputElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const objectUrls=useRef<string[]>([]);
  const [source,setSource]=useState<CropSource|null>(null);const [preview,setPreview]=useState(existingUrl||"");const [cropping,setCropping]=useState(false);const [zoom,setZoom]=useState(1);const [positionX,setPositionX]=useState(0);const [positionY,setPositionY]=useState(0);const [error,setError]=useState("");
  useEffect(()=>()=>{objectUrls.current.forEach(url=>URL.revokeObjectURL(url))},[]);
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas||!source)return;const context=canvas.getContext("2d");if(!context)return;const outputWidth=1500;const outputHeight=1000;const imageWidth=source.image.naturalWidth;const imageHeight=source.image.naturalHeight;const scale=Math.max(outputWidth/imageWidth,outputHeight/imageHeight)*zoom;const visibleWidth=outputWidth/scale;const visibleHeight=outputHeight/scale;const centerX=imageWidth/2+(positionX/100)*(imageWidth-visibleWidth)/2;const centerY=imageHeight/2+(positionY/100)*(imageHeight-visibleHeight)/2;const sx=Math.max(0,Math.min(imageWidth-visibleWidth,centerX-visibleWidth/2));const sy=Math.max(0,Math.min(imageHeight-visibleHeight,centerY-visibleHeight/2));context.clearRect(0,0,outputWidth,outputHeight);context.drawImage(source.image,sx,sy,visibleWidth,visibleHeight,0,0,outputWidth,outputHeight)},[source,zoom,positionX,positionY]);
  function selectFile(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setError("");if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError("รองรับเฉพาะ JPG, PNG และ WebP");return}if(file.size>8*1024*1024){setError("รูปต้องมีขนาดไม่เกิน 8 MB");return}const url=URL.createObjectURL(file);objectUrls.current.push(url);const image=new window.Image();image.onload=()=>{setSource({file,image,url});setZoom(1);setPositionX(0);setPositionY(0);setCropping(true)};image.onerror=()=>setError("ไม่สามารถอ่านไฟล์รูปนี้ได้");image.src=url;}
  async function applyCrop(){const canvas=canvasRef.current;if(!canvas||!source)return;const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.88));if(!blob){setError("ไม่สามารถ Crop รูปได้");return}const baseName=source.file.name.replace(/\.[^.]+$/,"")||"trip-cover";const croppedFile=new File([blob],`${baseName}-cover.jpg`,{type:"image/jpeg"});const url=URL.createObjectURL(blob);objectUrls.current.push(url);setPreview(url);setCropping(false);onChange(croppedFile)}
  function cancelCrop(){setCropping(false);setSource(null);if(inputRef.current)inputRef.current.value=""}
  return <div className="cover-picker">
    {!cropping&&<label className="upload-field cover-upload"><span className="upload-preview" style={preview?{backgroundImage:`url("${preview}")`}:undefined}>{!preview&&<ImagePlus size={24}/>}</span><span><strong>{preview?"เปลี่ยนรูปหน้าปก":"เพิ่มรูปหน้าปก"}</strong><small>ระบบจะ Crop เป็นโปสการ์ดแนวนอน 4×6 · JPG, PNG หรือ WebP</small></span><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={selectFile}/></label>}
    {cropping&&<div className="cover-cropper"><div className="crop-head"><div><strong>จัดตำแหน่งรูปหน้าปก</strong><small>ภาพที่ได้เป็นโปสการ์ดแนวนอน 4×6</small></div><button type="button" onClick={cancelCrop}>ยกเลิก</button></div><div className="crop-canvas-wrap"><canvas ref={canvasRef} width={1500} height={1000}/><span>4 × 6</span></div><div className="crop-controls"><label><span>ซูม</span><input type="range" min="1" max="2.5" step="0.01" value={zoom} onChange={event=>setZoom(Number(event.target.value))}/></label><label><span>ซ้าย–ขวา</span><input type="range" min="-100" max="100" value={positionX} onChange={event=>setPositionX(Number(event.target.value))}/></label><label><span>บน–ล่าง</span><input type="range" min="-100" max="100" value={positionY} onChange={event=>setPositionY(Number(event.target.value))}/></label></div><button type="button" className="crop-apply" onClick={applyCrop}>ใช้ภาพนี้เป็นหน้าปก</button></div>}
    {error&&<p className="cover-error">{error}</p>}
  </div>;
}

function ModalForm({modal,trip,day,close,submit,deleteItem,notify}:{modal:NonNullable<Modal>;trip:Trip|null;day:number;close:()=>void;submit:(data:Record<string,unknown>)=>Promise<void>;deleteItem:(item:Itinerary)=>Promise<void>;notify:(message:string)=>void}){
  const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  const [coverFile,setCoverFile]=useState<File|null>(null);
  const [costItems,setCostItems]=useState<Array<{key:string;value:string}>>(()=>modal.type==="place"&&modal.item?.cost_items?.length?modal.item.cost_items.map(item=>({key:item.key,value:moneyFormat(item.value)})):[]);
  const [pendingCostDelete,setPendingCostDelete]=useState<number|null>(null);
  const [pendingItemDelete,setPendingItemDelete]=useState(false);
  useEffect(()=>{const body=document.body;const scrollY=window.scrollY;const previous={overflow:body.style.overflow,position:body.style.position,top:body.style.top,width:body.style.width};body.style.overflow="hidden";body.style.position="fixed";body.style.top=`-${scrollY}px`;body.style.width="100%";return()=>{body.style.overflow=previous.overflow;body.style.position=previous.position;body.style.top=previous.top;body.style.width=previous.width;window.scrollTo(0,scrollY)}},[]);
  const outboundDate=modal.type==="trip"?localDate(modal.trip?.outbound_departure_at,modal.trip?.start_date||""):"";
  const returnFallback=modal.type==="trip"&&modal.trip?addDays(modal.trip.start_date,modal.trip.total_days-1):"";
  const returnDate=modal.type==="trip"?localDate(modal.trip?.return_departure_at,returnFallback):"";
  const amount=(f:FormData,name:string)=>Number(String(f.get(name)||"0").replace(/,/g,""));
  async function handle(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);try{if(modal.type==="trip"){let coverImageUrl=modal.trip?.cover_image_url||undefined;if(coverFile){const upload=new FormData();upload.set("file",coverFile);const response=await fetch("/api/uploads",{method:"POST",body:upload});const result=await response.json();if(!response.ok)throw new Error(result.error||"อัปโหลดรูปไม่สำเร็จ");coverImageUrl=result.url}await submit({name:f.get("name"),destination:f.get("destination"),outboundDate:f.get("outboundDate"),outboundTime:f.get("outboundTime"),returnDate:f.get("returnDate"),returnTime:f.get("returnTime"),budgetThb:amount(f,"budgetThb"),shoppingBudgetThb:amount(f,"shoppingBudgetThb"),coverImageUrl})}if(modal.type==="place"){const costs=costItems.filter(item=>item.key.trim()||item.value).map(item=>({key:item.key.trim(),value:Number(item.value.replace(/,/g,""))}));if(costs.some(item=>!item.key))throw new Error("กรุณาใส่ชื่อรายการราคาให้ครบ");const startTime=String(f.get("startTime"));const hour=Number(startTime.slice(0,2));const timeSlot=hour<12?"morning":hour<17?"afternoon":"evening";const common={placeName:f.get("placeName"),address:f.get("address"),transportNote:f.get("transportNote"),costItems:costs,dayNumber:Number(f.get("dayNumber")),timeSlot,startTime};if(modal.item)await submit(common);else await submit({...common,transportMode:f.get("transportMode")})}if(modal.type==="expense")await submit({tripId:trip?.id,title:f.get("title"),category:f.get("category"),expenseType:f.get("expenseType"),foreignAmount:amount(f,"foreignAmount"),currency:f.get("currency"),exchangeRate:Number(f.get("exchangeRate")),paymentMethod:f.get("paymentMethod"),spentAt:f.get("spentAt")});close()}catch(err){setError(err instanceof Error?err.message:"บันทึกไม่สำเร็จ");setSaving(false)}}
  const title=modal.type==="trip"?(modal.trip?"แก้ไขทริป":"สร้างทริปใหม่"):modal.type==="place"?(modal.item?"แก้ไขรายการ":"เพิ่มแผนเที่ยว"):"เพิ่มค่าใช้จ่าย";
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form className="modal" onSubmit={handle}><div className="modal-head"><h2>{title}</h2><button type="button" className="icon-btn" onClick={close}><X size={18}/></button></div><div className="form-grid">
    {modal.type==="trip"&&<><CoverImagePicker existingUrl={modal.trip?.cover_image_url} onChange={setCoverFile}/><div className="field"><label>ชื่อทริป</label><input name="name" required defaultValue={modal.trip?.name}/></div><div className="field"><label>เมืองหรือประเทศปลายทาง</label><input name="destination" required defaultValue={modal.trip?.destination}/></div><div className="form-row"><div className="field"><label>วันบินขาไป</label><input name="outboundDate" type="date" required defaultValue={outboundDate}/></div><div className="field"><label>เวลาเที่ยวบินขาไป</label><input name="outboundTime" type="time" required defaultValue={localTime(modal.trip?.outbound_departure_at)}/></div></div><div className="form-row"><div className="field"><label>วันเดินทางกลับ</label><input name="returnDate" type="date" required defaultValue={returnDate}/></div><div className="field"><label>เวลาเที่ยวบินกลับ</label><input name="returnTime" type="time" required defaultValue={localTime(modal.trip?.return_departure_at,"18:00")}/></div></div><div className="field"><label>งบหลัก (THB)</label><MoneyInput name="budgetThb" required defaultValue={modal.trip?.budget_thb||0}/></div><div className="field"><label>งบ Shopping แยก (THB)</label><MoneyInput name="shoppingBudgetThb" required defaultValue={modal.trip?.shopping_budget_thb||0}/></div></>}
    {modal.type==="place"&&<><div className="form-row"><div className="field"><label>วัน</label><select name="dayNumber" required defaultValue={modal.item?.day_number||day}>{Array.from({length:trip?.total_days||1},(_,index)=>index+1).map(number=><option key={number} value={number}>Day {number}</option>)}</select></div><div className="field"><label>เวลา</label><input name="startTime" type="time" required defaultValue={modal.item?.start_time?.slice(0,5)||"09:00"}/></div></div><p className="field-hint">เปลี่ยนแผนได้ทุกเมื่อ ระบบจะย้ายรายการไปยังวันที่เลือกและเรียงตามเวลาให้อัตโนมัติ</p><div className="field"><label>ชื่อรายการ</label><input name="placeName" required defaultValue={modal.item?.place_name}/></div><div className="field"><label>สถานที่ / ที่อยู่</label><input name="address" defaultValue={modal.item?.address||""}/></div>{!modal.item&&<div className="field"><label>วิธีเดินทางไปจุดถัดไป</label><select name="transportMode"><option>เดิน</option><option>รถไฟ</option><option>รถยนต์</option><option>รถบัส</option><option>แท็กซี่</option></select></div>}<div className="field"><label>รายละเอียด</label><textarea name="transportNote" rows={3} defaultValue={modal.item?.transport_note||""} placeholder="รายละเอียดร้าน การเดินทาง หรือสิ่งที่ต้องจำ"/></div><div className="cost-editor"><div className="cost-editor-head"><div><strong>รายการราคา</strong><small>เพิ่มได้หลายค่า เช่น ร้านอาหาร และค่าเดินทาง</small></div><button type="button" className="text-btn" onClick={()=>setCostItems(old=>[...old,{key:"",value:""}])}><Plus size={14}/>เพิ่มราคา</button></div>{costItems.length===0?<button type="button" className="empty-cost" onClick={()=>setCostItems([{key:"",value:""}])}>+ เพิ่มราคาแบบ Key–Value</button>:<div className="cost-editor-list">{costItems.map((cost,index)=><div className="cost-editor-row" key={index}><input aria-label="ชื่อรายการราคา" placeholder="เช่น ร้านราเมง" value={cost.key} onChange={e=>setCostItems(old=>old.map((item,i)=>i===index?{...item,key:e.target.value}:item))}/><input aria-label="จำนวนเงิน" inputMode="decimal" placeholder="0" value={cost.value} onChange={e=>setCostItems(old=>old.map((item,i)=>i===index?{...item,value:moneyFormat(e.target.value)}:item))}/><button type="button" onClick={()=>setPendingCostDelete(index)} aria-label="ลบราคา"><X size={15}/></button></div>)}</div>}</div></>}
    {modal.type==="expense"&&<><div className="field"><label>รายการ</label><input name="title" required/></div><div className="field"><label>หมวดหมู่</label><select name="category"><option>อาหาร</option><option>เดินทาง</option><option>ที่พัก</option><option value="shopping">Shopping</option><option>อื่น ๆ</option></select></div><div className="field"><label>ประเภท</label><select name="expenseType"><option value="actual">จ่ายจริง Actual</option><option value="budget">งบประมาณ Budget</option></select></div><div className="field"><label>ยอดเงิน</label><MoneyInput name="foreignAmount" required/></div><div className="field"><label>สกุลเงิน</label><select name="currency"><option>THB</option><option>JPY</option><option>USD</option><option>EUR</option><option>KRW</option></select></div><div className="field"><label>อัตราแลกเปลี่ยนเป็น THB</label><input name="exchangeRate" type="number" min="0.000001" step="0.000001" defaultValue="1" required/></div><div className="field"><label>วันที่</label><input name="spentAt" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></div><div className="field"><label>ช่องทางชำระ</label><select name="paymentMethod"><option>เงินสด</option><option>โอนเงิน</option><option>บัตรเครดิต</option></select></div></>}
  </div>{error&&<p className="login-error">{error}</p>}<div className="modal-submit-actions"><button className="primary-btn" disabled={saving}>{saving?"กำลังอัปโหลดและบันทึก…":"บันทึก"}</button>{modal.type==="place"&&modal.item&&<button type="button" className="delete-record-btn" onClick={()=>setPendingItemDelete(true)} disabled={saving}><Trash2 size={15}/>ลบรายการนี้</button>}</div></form>{pendingCostDelete!==null&&<ConfirmDialog confirmation={{title:"ลบรายการราคานี้?",description:`รายการ “${costItems[pendingCostDelete]?.key||"ยังไม่ได้ตั้งชื่อ"}” จะถูกนำออกจากแผน`,onConfirm:()=>{setCostItems(old=>old.filter((_,index)=>index!==pendingCostDelete));notify("ลบรายการราคาแล้ว");setPendingCostDelete(null)}}} close={()=>setPendingCostDelete(null)}/>} {pendingItemDelete&&modal.type==="place"&&modal.item&&<ConfirmDialog confirmation={{title:`ลบ “${modal.item.place_name}”?`,description:"รายการนี้ รวมถึงรายละเอียดและราคาที่บันทึกไว้จะถูกลบออกจาก Timeline",confirmLabel:"ลบรายการ",onConfirm:async()=>{await deleteItem(modal.item!);setPendingItemDelete(false);close()}}} close={()=>setPendingItemDelete(false)}/>}</div>;
}

export function BNTripApp({authenticated=false,page="dashboard",tripId}:{authenticated?:boolean;page?:Screen;tripId?:string}){
  const router=useRouter();const [dark,setDark]=useState(false);const [lang,setLang]=useState<Lang>("TH");const [trips,setTrips]=useState<Trip[]>([]);const [selected,setSelected]=useState<Trip|null>(null);const [itineraries,setItineraries]=useState<Itinerary[]>([]);const [expenses,setExpenses]=useState<Expense[]>([]);const [modal,setModal]=useState<Modal>(null);const [confirmation,setConfirmation]=useState<Confirmation|null>(null);const [toast,setToast]=useState("");const [loading,setLoading]=useState(true);const [activeDay,setActiveDay]=useState(1);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{setDark(document.documentElement.classList.contains("dark"));const saved=localStorage.getItem("bn-lang") as Lang|null;if(saved)setLang(saved)});return()=>cancelAnimationFrame(frame)},[]);
  useEffect(()=>{if(!authenticated)return;fetch("/api/trips").then(r=>r.json()).then((data:Trip[])=>{const rows=Array.isArray(data)?data:[];setTrips(rows);setSelected(tripId?rows.find(t=>t.id===tripId)||null:null);setLoading(false)}).catch(()=>setLoading(false))},[authenticated,tripId]);
  useEffect(()=>{if(!selected)return;Promise.all([fetch(`/api/trips/${selected.id}/itineraries`).then(r=>r.json()),fetch(`/api/expenses?tripId=${selected.id}`).then(r=>r.json())]).then(([i,e])=>{setItineraries(Array.isArray(i)?i:[]);setExpenses(Array.isArray(e)?e:[])})},[selected]);
  if(!authenticated)return <LoginScreen/>;
  const flash=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),2400)};
  const toggleTheme=()=>{const next=!dark;setDark(next);document.documentElement.classList.toggle("dark",next);localStorage.setItem("bn-theme",next?"dark":"light")};
  const request=async(url:string,options?:RequestInit)=>{const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(data.error||"บันทึกไม่สำเร็จ");return data};
  async function saveModal(data:Record<string,unknown>){if(!modal)return;if(modal.type==="trip"){const saved=await request(modal.trip?`/api/trips/${modal.trip.id}`:"/api/trips",{method:modal.trip?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});setTrips(old=>modal.trip?old.map(t=>t.id===saved.id?saved:t):[saved,...old]);setSelected(saved);flash(modal.trip?"แก้ไขทริปแล้ว":"สร้างทริปแล้ว เลือกสิ่งที่ต้องการจัดการได้เลย");router.push(`/trips/${saved.id}`)}if(modal.type==="place"&&selected){const editing=modal.item;const saved=await request(editing?`/api/itineraries/${editing.id}`:`/api/trips/${selected.id}/itineraries`,{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});setItineraries(old=>{const next:Itinerary[]=editing?old.map(item=>item.id===saved.id?saved:item):[...old,saved];return next.sort((a,b)=>a.day_number-b.day_number||(a.start_time||"99:99").localeCompare(b.start_time||"99:99"))});setActiveDay(saved.day_number);flash(editing?"อัปเดตวัน เวลา และรายละเอียดแล้ว":"เพิ่มแผนเที่ยวและเรียง Timeline แล้ว")}if(modal.type==="expense"){const saved=await request("/api/expenses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});setExpenses(old=>[saved,...old]);flash("บันทึกค่าใช้จ่ายและ Stamp ค่าเงินแล้ว")}}
  async function removeItinerary(item:Itinerary){await request(`/api/itineraries/${item.id}`,{method:"DELETE"});setItineraries(old=>old.filter(row=>row.id!==item.id));flash("ลบรายการออกจาก Timeline แล้ว")}
  async function removeTrip(trip:Trip){await request(`/api/trips/${trip.id}`,{method:"DELETE"});setTrips(old=>old.filter(t=>t.id!==trip.id));if(selected?.id===trip.id)setSelected(null);flash("ลบทริปสำเร็จแล้ว");router.push("/")}
  const askDeleteTrip=(trip:Trip)=>setConfirmation({title:`ลบทริป “${trip.name}”?`,description:"แผนเที่ยว ค่าใช้จ่าย และข้อมูลทั้งหมดในทริปนี้จะถูกลบถาวร",confirmLabel:"ลบทริป",onConfirm:()=>removeTrip(trip)});
  const selectTrip=(trip:Trip)=>router.push(`/trips/${trip.id}`);
  const logout=async()=>{await fetch("/api/auth/logout",{method:"POST"});location.href="/"};
  const content=loading?<div className="card">กำลังโหลดข้อมูล…</div>:page==="dashboard"?<Dashboard trips={trips} selectTrip={selectTrip} createTrip={()=>setModal({type:"trip"})} editTrip={t=>setModal({type:"trip",trip:t})} deleteTrip={askDeleteTrip}/>:page==="trip"&&selected?<TripHub trip={selected} items={itineraries} day={activeDay} setDay={setActiveDay} back={()=>router.push("/")} openExpenses={()=>router.push(`/trips/${selected.id}/expenses`)} editTrip={()=>setModal({type:"trip",trip:selected})} addPlace={day=>{setActiveDay(day);setModal({type:"place"})}} editPlace={item=>{setActiveDay(item.day_number);setModal({type:"place",item})}}/>:page==="timeline"&&selected?<TimelineScreen trip={selected} items={itineraries} day={activeDay} setDay={setActiveDay} addPlace={()=>setModal({type:"place"})} back={()=>router.push(`/trips/${selected.id}`)}/>:page==="expenses"&&selected?<ExpensesScreen trip={selected} expenses={expenses} addExpense={()=>setModal({type:"expense"})} back={()=>router.push(`/trips/${selected.id}`)}/>:page==="settings"?<SettingsScreen dark={dark} toggleTheme={toggleTheme} lang={lang} setLang={value=>{setLang(value);localStorage.setItem("bn-lang",value)}} logout={logout}/>:<EmptyState title="ไม่พบทริปนี้" description="ทริปอาจถูกลบหรือไม่ได้อยู่ในบัญชีนี้" action="กลับไปเลือกทริป" onClick={()=>router.push("/")}/>;
  return <div className="app-shell flow-shell">{toast&&<div className="toast toast-success" role="status"><CheckCircle2 size={17}/>{toast}</div>}<main><header className="mobile-head flow-header"><Brand/><nav className="mobile-actions" aria-label="เมนูหลัก"><button className={`icon-btn ${page==="dashboard"?"active":""}`} onClick={()=>router.push("/")} aria-label="หน้าแรก" title="หน้าแรก"><House size={18}/></button><button className={`icon-btn ${page==="settings"?"active":""}`} onClick={()=>router.push("/settings")} aria-label="ตั้งค่า" title="ตั้งค่า"><Settings2 size={18}/></button></nav></header>{content}</main>{modal&&<ModalForm modal={modal} trip={selected} day={activeDay} close={()=>setModal(null)} submit={saveModal} deleteItem={removeItinerary} notify={flash}/>} {confirmation&&<ConfirmDialog confirmation={confirmation} close={()=>setConfirmation(null)}/>}</div>;
}
