"use client";

import { upload } from "@vercel/blob/client";
import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import { AlertTriangle, CalendarDays, Check, ChevronDown, Clock, FileText, Luggage, Plane, Plus, RefreshCw, Trash2, Upload, X } from "lucide-react";
import { prepareDocumentFile } from "@/src/lib/client-image-compression";

type Member={id:string;display_name:string|null;email:string|null;avatar_url:string|null;role:"owner"|"collaborator"};
type Passenger={user_id:string;seat_number:string|null;meal_preference:string|null;baggage_note:string|null;display_name:string|null;avatar_url:string|null};
type FlightDocument={id:string;title:string;original_filename:string;mime_type:string};
type Segment={id:string;journey_type:"outbound"|"return"|"internal";segment_order:number;airline_code:string;airline_name:string;flight_number:string;departure_airport_code:string;departure_airport_name:string;arrival_airport_code:string;arrival_airport_name:string;scheduled_departure_at:string;scheduled_arrival_at:string;entered_departure_local_text:string|null;entered_arrival_local_text:string|null;latest_departure_at:string|null;latest_arrival_at:string|null;departure_terminal:string|null;departure_gate:string|null;arrival_terminal:string|null;arrival_gate:string|null;status:string;booking_reference:string|null;cabin_class:string|null;baggage_note:string|null;ticket_price:string|null;ticket_currency:string|null;ticket_exchange_rate:string|null;ticket_rate_date:string|null;last_synced_at:string|null;provider:string|null;passengers:Passenger[];documents:FlightDocument[]};
type Payload={segments:Segment[];syncConfigured:boolean;documentUploadMode:"client"|"server"};

async function json<T>(url:string,options?:RequestInit){const response=await fetch(url,options);const body=await response.json();if(!response.ok)throw new Error(body.error||"ทำรายการไม่สำเร็จ");return body as T}
const labels={outbound:"ขาไป",return:"ขากลับ",internal:"เที่ยวบินภายในทริป"} as const;
const ticketCurrencies=[{value:"THB",label:"บาท (THB)"},{value:"CNY",label:"หยวน (CNY)"},{value:"JPY",label:"เยน (JPY)"},{value:"USD",label:"ดอลลาร์ (USD)"},{value:"EUR",label:"ยูโร (EUR)"},{value:"GBP",label:"ปอนด์ (GBP)"},{value:"KRW",label:"วอน (KRW)"},{value:"SGD",label:"SGD"},{value:"HKD",label:"HKD"},{value:"TWD",label:"TWD"},{value:"AUD",label:"AUD"}] as const;
function inputDate(value?:string|null){if(!value)return "";const date=new Date(value);const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
// Trip departure/return columns are PostgreSQL `timestamp` values: they are wall-clock
// times chosen by the user, not UTC instants. The API serializes them with a trailing Z,
// so converting through Date would add the device offset again (22:30 became 05:30 on
// an iPhone in Bangkok). Preserve the stored date and time verbatim for form defaults.
function tripWallClock(value?:string|null){if(!value)return "";return value.replace(" ","T").slice(0,16)}
function datePart(value:string){return value.slice(0,10)}function timePart(value:string){return value.slice(11,16)}function plusHours(value:string,hours=4){return inputDate(new Date(new Date(value).getTime()+hours*3600000).toISOString())}
function displayDay(value:string,latest?:string|null){return new Date(latest||value).toLocaleDateString("th-TH",{day:"numeric",month:"short",year:"2-digit"})}
function displayTime(value:string,latest?:string|null){return new Date(latest||value).toLocaleTimeString("th-TH",{hour:"2-digit",minute:"2-digit"})}
function localDay(value:string|null,fallback:string,latest?:string|null){if(!value)return displayDay(fallback,latest);return new Date(`${value.slice(0,10)}T00:00:00`).toLocaleDateString("th-TH",{day:"numeric",month:"short",year:"2-digit"})}
function localTime(value:string|null,fallback:string,latest?:string|null){return value?.slice(11,16)||displayTime(fallback,latest)}
function airportName(value:string){return value.replace(/\s+(?:International(?:\s+Airport)?|Intl\.?|Int['’]l\.?)$/i,"").trim()||value}
function flightHasEnded(item:Segment){return new Date(item.latest_arrival_at||item.scheduled_arrival_at).getTime()<Date.now()}
function moneyFormat(value:string|number){const clean=String(value??"").replace(/,/g,"").replace(/[^\d.]/g,"");if(!clean)return "";const [whole,decimal]=clean.split(".");return `${Number(whole||0).toLocaleString("en-US")}${decimal!==undefined?`.`+decimal.slice(0,2):""}`}
function TicketMoneyInput({name,defaultValue}:{name:string;defaultValue?:string|number}){const [value,setValue]=useState(()=>moneyFormat(defaultValue??""));return <input name={name} inputMode="decimal" value={value} onChange={event=>setValue(moneyFormat(event.target.value))} placeholder="ไม่ระบุ"/>}
function FlightDateTimeInput({name,type,value,onChange,label}:{name:string;type:"date"|"time";value:string;onChange:(value:string)=>void;label:string}){const display=type==="date"&&value?new Date(`${value}T00:00:00`).toLocaleDateString("th-TH-u-ca-gregory",{day:"numeric",month:"short",year:"numeric"}):value||(type==="date"?"เลือกวันที่":"เลือกเวลา");const Icon=type==="date"?CalendarDays:Clock;return <label className="native-picker-control"><span className="native-picker-value">{display}</span><Icon size={18} aria-hidden="true"/><input aria-label={label} lang="th-TH-u-ca-gregory" name={name} type={type} value={value} required onChange={event=>onChange(event.target.value)}/></label>}

export function TripFlights({tripId,members,tripOutboundAt,tripReturnAt,canDelete,notify,onChanged,onOpenDocuments}:{tripId:string;members:Member[];tripOutboundAt:string|null;tripReturnAt:string|null;canDelete:boolean;notify?:(message:string)=>void;onChanged?:()=>void|Promise<void>;onOpenDocuments?:()=>void}){
  const [data,setData]=useState<Payload>({segments:[],syncConfigured:false,documentUploadMode:"server"});
  const outboundDefault=tripWallClock(tripOutboundAt)||inputDate(new Date().toISOString());const returnDefault=tripWallClock(tripReturnAt)||plusHours(outboundDefault,24);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [editing,setEditing]=useState<Segment|"new"|null>(null);const [saving,setSaving]=useState(false);const [journeyType,setJourneyType]=useState<Segment["journey_type"]>("outbound");const [departureValue,setDepartureValue]=useState(outboundDefault);const [arrivalValue,setArrivalValue]=useState(plusHours(outboundDefault));const [manualEntry,setManualEntry]=useState(false);const [selectedPassengerIds,setSelectedPassengerIds]=useState<string[]>(()=>members.map(member=>member.id));const [ticketCurrency,setTicketCurrency]=useState("THB");const [ticketExchangeRate,setTicketExchangeRate]=useState(1);const [ticketRateDate,setTicketRateDate]=useState(datePart(outboundDefault));const [ticketRateLoading,setTicketRateLoading]=useState(false);const [deleteTarget,setDeleteTarget]=useState<Segment|null>(null);const [flightDocumentName,setFlightDocumentName]=useState("");const fileRef=useRef<HTMLInputElement>(null);
  async function load(){setLoading(true);try{setData(await json<Payload>(`/api/trips/${tripId}/flights`,{cache:"no-store"}));setError("")}catch(reason){setError(reason instanceof Error?reason.message:"โหลดเที่ยวบินไม่สำเร็จ")}finally{setLoading(false)}}
  useEffect(()=>{let active=true;void json<Payload>(`/api/trips/${tripId}/flights`,{cache:"no-store"}).then(result=>{if(active){setData(result);setError("");setLoading(false)}}).catch(reason=>{if(active){setError(reason instanceof Error?reason.message:"โหลดเที่ยวบินไม่สำเร็จ");setLoading(false)}});return()=>{active=false}
    // The request is intentionally keyed only by trip identity.
  },[tripId]);
  useEffect(()=>{if(!editing)return;document.documentElement.classList.add("sheet-open");return()=>document.documentElement.classList.remove("sheet-open")},[editing]);
  useEffect(()=>{if(!editing||ticketCurrency==="THB")return;const requestedDate=datePart(departureValue);const controller=new AbortController();void (async()=>{await Promise.resolve();setTicketRateLoading(true);try{const response=await fetch(`/api/exchange-rate?currency=${ticketCurrency}&date=${requestedDate}`,{signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body.error);setTicketExchangeRate(Number(body.rate));setTicketRateDate(String(body.date||requestedDate))}catch(reason){if((reason as Error).name!=="AbortError")setError(reason instanceof Error?reason.message:"โหลดอัตราแลกเปลี่ยนไม่สำเร็จ")}finally{if(!controller.signal.aborted)setTicketRateLoading(false)}})();return()=>controller.abort()},[editing,ticketCurrency,departureValue]);
  const groups=useMemo(()=>({outbound:data.segments.filter(item=>item.journey_type==="outbound"),internal:data.segments.filter(item=>item.journey_type==="internal"),return:data.segments.filter(item=>item.journey_type==="return")}),[data.segments]);
  function openNew(){setJourneyType("outbound");setDepartureValue(outboundDefault);setArrivalValue(plusHours(outboundDefault));setManualEntry(false);setSelectedPassengerIds(members.map(member=>member.id));setTicketCurrency("THB");setTicketExchangeRate(1);setTicketRateDate(datePart(outboundDefault));setEditing("new")}
  function openEdit(item:Segment){const enteredDeparture=item.entered_departure_local_text||inputDate(item.scheduled_departure_at);const enteredArrival=item.entered_arrival_local_text||inputDate(item.scheduled_arrival_at);setJourneyType(item.journey_type);setDepartureValue(enteredDeparture);setArrivalValue(enteredArrival);setManualEntry(item.provider==="manual");setSelectedPassengerIds(item.passengers.map(passenger=>passenger.user_id));setTicketCurrency(item.ticket_currency||"THB");setTicketExchangeRate(Number(item.ticket_exchange_rate||1));setTicketRateDate(item.ticket_rate_date||datePart(enteredDeparture));setFlightDocumentName("");setEditing(item)}
  function changeJourney(type:Segment["journey_type"]){setJourneyType(type);if(editing==="new"){const departure=type==="return"?returnDefault:outboundDefault;setDepartureValue(departure);setArrivalValue(plusHours(departure))}}
  async function save(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();
    if(!editing)return;
    if(!selectedPassengerIds.length){setError("กรุณาเลือกผู้โดยสารอย่างน้อย 1 คน");return}
    const form=new FormData(event.currentTarget);
    const ticketPrice=Number(String(form.get("ticketPrice")||"0").replace(/,/g,""));
    if(ticketPrice>0&&(ticketRateLoading||ticketExchangeRate<=0)){setError("กรุณารออัตราแลกเปลี่ยน");return}
    const isNew=editing==="new";
    const endpoint=isNew?`/api/trips/${tripId}/flights`:`/api/trips/${tripId}/flights/${editing.id}`;
    setSaving(true);setError("");
    const passengerRows=members.filter(member=>selectedPassengerIds.includes(member.id)).map(member=>({userId:member.id,seatNumber:String(form.get(`seat:${member.id}`)||""),mealPreference:String(form.get(`meal:${member.id}`)||""),baggageNote:String(form.get(`bag:${member.id}`)||"")}));
    const departureLocal=`${form.get("departureDate")}T${form.get("departureTime")}`;
    const arrivalLocal=`${form.get("arrivalDate")}T${form.get("arrivalTime")}`;
    const body={journeyType:String(form.get("journeyType")),segmentOrder:Number(form.get("segmentOrder")),flightIdent:String(form.get("flightIdent")),scheduledDepartureAt:new Date(departureLocal).toISOString(),scheduledArrivalAt:new Date(arrivalLocal).toISOString(),enteredDepartureLocal:departureLocal,enteredArrivalLocal:arrivalLocal,ticketPrice,ticketCurrency,ticketExchangeRate:ticketCurrency==="THB"?1:ticketExchangeRate,ticketRateDate:ticketCurrency==="THB"?datePart(departureValue):ticketRateDate,bookingReference:String(form.get("bookingReference")),cabinClass:String(form.get("cabinClass")),baggageNote:String(form.get("baggageNote")),passengers:passengerRows,manualAirlineName:String(form.get("manualAirlineName")||""),manualDepartureAirportCode:String(form.get("manualDepartureAirportCode")||""),manualDepartureAirportName:String(form.get("manualDepartureAirportName")||""),manualArrivalAirportCode:String(form.get("manualArrivalAirportCode")||""),manualArrivalAirportName:String(form.get("manualArrivalAirportName")||"")};
    try{await json(endpoint,{method:isNew?"POST":"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setEditing(null);await Promise.all([load(),onChanged?.()]);notify?.(ticketPrice>0?(isNew?"เพิ่มเที่ยวบิน แผน และค่าใช้จ่ายแล้ว":"อัปเดตเที่ยวบิน แผน และค่าใช้จ่ายแล้ว"):(isNew?"เพิ่มเที่ยวบินและแผนแล้ว":"อัปเดตเที่ยวบินและแผนแล้ว"))}catch(reason){setError(reason instanceof Error?reason.message:"บันทึกไม่สำเร็จ")}finally{setSaving(false)}
  }
  async function remove(item:Segment){setSaving(true);try{await json(`/api/trips/${tripId}/flights/${item.id}`,{method:"DELETE"});setDeleteTarget(null);setEditing(null);await Promise.all([load(),onChanged?.()]);notify?.("ลบเที่ยวบิน แผน และค่าใช้จ่ายแล้ว")}catch(reason){setError(reason instanceof Error?reason.message:"ลบไม่สำเร็จ")}finally{setSaving(false)}}
  async function sync(item:Segment){try{await json(`/api/trips/${tripId}/flights/${item.id}/sync`,{method:"POST"});await load();notify?.("อัปเดตสถานะเที่ยวบินแล้ว")}catch(reason){setError(reason instanceof Error?reason.message:"ซิงก์ไม่สำเร็จ")}}
  async function uploadFile(item:Segment,form:FormData){const source=fileRef.current?.files?.[0];const title=String(form.get("documentTitle")||"").trim();if(!source||!title)throw new Error("กรุณากรอกชื่อและเลือกไฟล์");const file=await prepareDocumentFile(source);if(data.documentUploadMode==="client"){const extension=file.name.split(".").pop()?.replace(/[^a-z0-9]/gi,"")||"bin";const pathname=`documents/${tripId}/doc-${crypto.randomUUID()}.${extension}`;const blob=await upload(pathname,file,{access:"private",handleUploadUrl:`/api/trips/${tripId}/documents/client-upload`,clientPayload:JSON.stringify({size:file.size})});await json(`/api/trips/${tripId}/documents`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,originalFilename:file.name,mimeType:file.type,size:file.size,blobUrl:blob.url,pathname:blob.pathname,flightSegmentId:item.id})})}else{const payload=new FormData();payload.set("title",title);payload.set("file",file);payload.set("flightSegmentId",item.id);const response=await fetch(`/api/trips/${tripId}/documents`,{method:"POST",body:payload});const body=await response.json();if(!response.ok)throw new Error(body.error)}if(fileRef.current)fileRef.current.value="";setFlightDocumentName("");await load();notify?.("แนบเอกสารเที่ยวบินแล้ว")}
  const edit=editing==="new"?null:editing;const defaultOrder=editing==="new"?groups[journeyType].length:edit?.segment_order||0;const historicalEntry=editing==="new"&&new Date(departureValue).getTime()<Date.now()-10*24*60*60*1000;const showManualEntry=manualEntry||historicalEntry;
  if(loading)return <div className="flight-empty">กำลังโหลดเที่ยวบิน…</div>;
  return <section className="flight-panel">
    <div className="toolbar expense-toolbar flight-toolbar"><div><h2>เที่ยวบินของทริป</h2><p className="page-sub">ดึงสายการบิน สนามบิน และสถานะล่าสุดจากเลขเที่ยวบิน</p></div></div>
    {error&&!editing&&<div className="form-error">{error}</div>}
    {!data.segments.length?<div className="flight-empty"><Plane size={32}/><strong>ยังไม่มีเที่ยวบิน</strong><span>เพิ่มเที่ยวบินแรก แล้วระบบจะแยกขาไป ขากลับ และช่วงต่อเครื่องให้อัตโนมัติ</span></div>:
      (["outbound","internal","return"] as const).map(type=>groups[type].length?<div className="flight-group" key={type}><h3>{labels[type]} <small>{groups[type].length} ช่วงบิน</small></h3>{groups[type].map((item,index)=><article className={`flight-card flight-card-compact ${flightHasEnded(item)?"is-past-flight":""}`} key={item.id} role="button" tabIndex={0} aria-label={`แก้ไขเที่ยวบิน ${item.airline_code} ${item.flight_number}`} onClick={()=>openEdit(item)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openEdit(item)}}}>
        <div className="flight-card-top">
          <div className="flight-card-identity">
            {item.passengers.length>0&&<div className="flight-passenger-stack" aria-label={`${item.passengers.length} ผู้โดยสาร`}>{item.passengers.slice(0,3).map(passenger=>passenger.avatar_url?<Image key={passenger.user_id} src={passenger.avatar_url} alt={passenger.display_name||"ผู้โดยสาร"} width={30} height={30} unoptimized/>:<span key={passenger.user_id}>{(passenger.display_name||"?")[0]}</span>)}{item.passengers.length>3&&<b>+{item.passengers.length-3}</b>}</div>}
            <div className="flight-number"><span><Plane className="flight-airline-icon" size={11}/>{item.airline_name||item.airline_code}</span><strong>{item.airline_code} {item.flight_number}</strong></div>
          </div>
          <div className={`flight-status status-${item.status.toLowerCase().replace(/\s/g,"-")}`}>{item.status||"scheduled"}</div>
          {!flightHasEnded(item)&&<button type="button" className="icon-btn flight-sync-top" onClick={event=>{event.stopPropagation();void sync(item)}} disabled={!data.syncConfigured} aria-label="รีเฟรชข้อมูลเที่ยวบิน"><RefreshCw size={16}/></button>}
        </div>
        <div className="flight-route-compact">
          <div className="flight-airport-block">
            <span className="flight-route-label">ต้นทาง</span>
            <strong>{item.departure_airport_code}</strong>
            <em>{item.departure_airport_name?airportName(item.departure_airport_name):"รอข้อมูลสนามบิน"}</em>
            <b>{localTime(item.entered_departure_local_text,item.scheduled_departure_at,item.latest_departure_at)}</b>
          </div>
          <div className="flight-route-path"><small className="flight-route-date"><CalendarDays size={10}/><span>{localDay(item.entered_departure_local_text,item.scheduled_departure_at,item.latest_departure_at)}</span><i>→</i><span>{localDay(item.entered_arrival_local_text,item.scheduled_arrival_at,item.latest_arrival_at)}</span></small><div className="flight-route-track"><span/><Plane size={23}/><span/></div></div>
          <div className="flight-airport-block is-arrival">
            <span className="flight-route-label">ปลายทาง</span>
            <strong>{item.arrival_airport_code}</strong>
            <em>{item.arrival_airport_name?airportName(item.arrival_airport_name):"รอข้อมูลสนามบิน"}</em>
            <b>{localTime(item.entered_arrival_local_text,item.scheduled_arrival_at,item.latest_arrival_at)}</b>
          </div>
        </div>
        <div className="flight-terminal-grid">
          <span>Terminal <b>{item.departure_terminal||"รออัปเดต"}</b> · Gate <b>{item.departure_gate||"รออัปเดต"}</b></span>
          <span>Terminal <b>{item.arrival_terminal||"รออัปเดต"}</b> · Gate <b>{item.arrival_gate||"รออัปเดต"}</b></span>
        </div>
        <div className="flight-card-footer">
          <div className="flight-meta">{index>0&&<span className="flight-connection-chip">ต่อเครื่องจาก {groups[type][index-1].arrival_airport_code}</span>}{item.ticket_price&&<span className="flight-ticket-price">{Number(item.ticket_price).toLocaleString("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2})} {item.ticket_currency}</span>}{item.booking_reference&&<span>Booking {item.booking_reference}</span>}{item.cabin_class&&<span>{item.cabin_class}</span>}{item.passengers.map(passenger=><span className="flight-seat-chip" key={`seat-${passenger.user_id}`} aria-label={`${passenger.display_name||"ผู้โดยสาร"} ที่นั่ง ${passenger.seat_number||"ยังไม่ระบุ"}`}>{passenger.avatar_url?<Image src={passenger.avatar_url} alt="" width={18} height={18} unoptimized/>:<i>{(passenger.display_name||"?")[0]}</i>}<b>{passenger.seat_number||"ยังไม่ระบุ"}</b></span>)}{item.baggage_note&&<span className="flight-baggage-chip"><Luggage size={13}/><b>สัมภาระรวม</b> {item.baggage_note}</span>}{item.documents.length>0&&<button type="button" className="flight-document-chip" onClick={event=>{event.stopPropagation();onOpenDocuments?.()}} aria-label={`เปิดเอกสาร ${item.documents.length} ไฟล์`}><FileText size={13}/> {item.documents.length}</button>}</div>
        </div>
      </article>)}</div>:null)}
    <button className="directory-fab flight-fab" type="button" onClick={openNew} aria-label="เพิ่มเที่ยวบิน"><Plus size={22}/><span>เพิ่มเที่ยวบิน</span></button>
    {editing&&<div className="modal-backdrop flight-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)setEditing(null)}}><form className="modal cost-sheet flight-sheet" onSubmit={save}><div className="modal-head"><div><h2>{edit?"แก้ไขเที่ยวบิน":"เพิ่มเที่ยวบิน"}</h2><p>กรอกเลขเที่ยวบิน แล้วระบบจะเติมข้อมูลที่ค้นหาได้ให้อัตโนมัติ</p></div><button type="button" className="icon-btn" onClick={()=>setEditing(null)} aria-label="ปิด"><X size={18}/></button></div>{error&&<div className="form-error">{error}</div>}<div className="flight-sheet-scroll"><div className="form-grid">
      <input name="segmentOrder" type="hidden" value={defaultOrder}/>
      <div className="form-row"><div className="field"><label>ประเภทการเดินทาง</label><select name="journeyType" value={journeyType} onChange={event=>changeJourney(event.target.value as Segment["journey_type"])}><option value="outbound">ขาไป</option><option value="return">ขากลับ</option><option value="internal">ภายในทริป / ต่อเครื่อง</option></select></div><div className="field"><label>เลขเที่ยวบิน</label><input name="flightIdent" required maxLength={16} defaultValue={edit?`${edit.airline_code}${edit.flight_number}`:""} placeholder="เช่น TG670" autoCapitalize="characters" spellCheck={false}/></div></div>
      <p className="field-note">ค้นหาข้อมูลเฉพาะตอนสร้างรายการ และเมื่อกดรีเฟรช</p>
      <div className="form-row flight-datetime-row"><div className="field"><label>วันออกเดินทาง</label><FlightDateTimeInput name="departureDate" type="date" value={datePart(departureValue)} onChange={value=>setDepartureValue(`${value}T${timePart(departureValue)||"09:00"}`)} label="วันออกเดินทาง"/></div><div className="field"><label>เวลาออกเดินทาง</label><FlightDateTimeInput name="departureTime" type="time" value={timePart(departureValue)} onChange={value=>setDepartureValue(`${datePart(departureValue)}T${value}`)} label="เวลาออกเดินทาง"/></div></div>
      <div className="form-row flight-datetime-row"><div className="field"><label>วันถึงปลายทาง</label><FlightDateTimeInput name="arrivalDate" type="date" value={datePart(arrivalValue)} onChange={value=>setArrivalValue(`${value}T${timePart(arrivalValue)||"13:00"}`)} label="วันถึงปลายทาง"/></div><div className="field"><label>เวลาถึงปลายทาง</label><FlightDateTimeInput name="arrivalTime" type="time" value={timePart(arrivalValue)} onChange={value=>setArrivalValue(`${datePart(arrivalValue)}T${value}`)} label="เวลาถึงปลายทาง"/></div></div>
      <label className="flight-manual-toggle"><input type="checkbox" checked={showManualEntry} disabled={historicalEntry} onChange={event=>setManualEntry(event.target.checked)}/><span className="split-checkmark" aria-hidden="true"/><strong>กรอกข้อมูลเที่ยวบินด้วยตนเอง</strong></label>
      {showManualEntry&&<div className="flight-manual-history"><div><strong>{historicalEntry?"เที่ยวบินย้อนหลัง":"ข้อมูลเส้นทางแบบกรอกเอง"}</strong><small>{historicalEntry?"บัญชี Personal ค้นหาประวัติย้อนหลังไม่ได้ กรุณาระบุเส้นทางเพื่อบันทึกรายการ":"ใช้เมื่อลองค้นหา API แล้วไม่พบเที่ยวบิน ระบบยังสร้าง Timeline ค่าใช้จ่าย ผู้โดยสาร และเอกสารให้เหมือนเดิม"}</small></div><div className="form-row"><div className="field"><label>รหัสสนามบินต้นทาง</label><input name="manualDepartureAirportCode" required maxLength={4} defaultValue={edit?.departure_airport_code||""} placeholder="เช่น BKK" autoCapitalize="characters"/></div><div className="field"><label>รหัสสนามบินปลายทาง</label><input name="manualArrivalAirportCode" required maxLength={4} defaultValue={edit?.arrival_airport_code||""} placeholder="เช่น CTS" autoCapitalize="characters"/></div></div><div className="form-row"><div className="field"><label>ชื่อสนามบินต้นทาง <small>ไม่บังคับ</small></label><input name="manualDepartureAirportName" defaultValue={edit?.departure_airport_name||""} placeholder="เช่น Suvarnabhumi"/></div><div className="field"><label>ชื่อสนามบินปลายทาง <small>ไม่บังคับ</small></label><input name="manualArrivalAirportName" defaultValue={edit?.arrival_airport_name||""} placeholder="เช่น New Chitose"/></div></div><div className="field"><label>ชื่อสายการบิน <small>ไม่บังคับ</small></label><input name="manualAirlineName" defaultValue={edit?.airline_name||""} placeholder="เช่น Thai Airways International"/></div></div>}
      <div className="form-row flight-ticket-row"><div className="field"><label>ราคาตั๋วรวมทั้งหมด <small>ไม่บังคับ</small></label><TicketMoneyInput name="ticketPrice" defaultValue={edit?.ticket_price||""}/></div><div className="field"><label>สกุลเงิน</label><select value={ticketCurrency} onChange={event=>{const currency=event.target.value;setTicketCurrency(currency);if(currency==="THB"){setTicketExchangeRate(1);setTicketRateLoading(false)}}}>{ticketCurrencies.map(currency=><option value={currency.value} key={currency.value}>{currency.label}</option>)}</select></div></div>
      <p className="flight-rate-note">{ticketRateLoading?"กำลังโหลดอัตราแลกเปลี่ยน…":ticketCurrency==="THB"?"ถ้ากรอกราคา ระบบจะเพิ่มค่าใช้จ่ายและหารตามผู้โดยสารที่เลือก":`1 ${ticketCurrency} = ${ticketExchangeRate.toFixed(5)} THB · เรตวันที่ ${ticketRateDate}`}</p>
      <details className="flight-optional-details"><summary><span>ข้อมูลการจองและสัมภาระ</span><small>ไม่บังคับ</small><ChevronDown size={16}/></summary><div className="flight-optional-fields"><div className="form-row"><div className="field"><label>Booking reference</label><input name="bookingReference" defaultValue={edit?.booking_reference||""}/></div><div className="field"><label>ชั้นโดยสาร</label><input name="cabinClass" defaultValue={edit?.cabin_class||"Economy"} placeholder="Economy"/></div></div><div className="field"><label>สัมภาระรวม</label><textarea name="baggageNote" defaultValue={edit?.baggage_note||""}/></div></div></details>
      <div className="flight-passengers"><div className="flight-passenger-heading"><div><h3>ผู้โดยสารเที่ยวบินนี้</h3><small>เลือกคนที่เดินทางในเที่ยวบินนี้</small></div><button type="button" onClick={()=>setSelectedPassengerIds(selectedPassengerIds.length===members.length?[]:members.map(member=>member.id))}>{selectedPassengerIds.length===members.length?"ยกเลิกทั้งหมด":"เลือกทุกคน"}</button></div><div className="flight-passenger-picker">{members.map(member=>{const selected=selectedPassengerIds.includes(member.id);return <label className={selected?"selected":""} key={member.id}><input type="checkbox" checked={selected} onChange={event=>setSelectedPassengerIds(current=>event.target.checked?[...new Set([...current,member.id])]:current.filter(id=>id!==member.id))}/>{member.avatar_url?<Image src={member.avatar_url} alt="" width={36} height={36} unoptimized/>:<span className="flight-passenger-fallback">{(member.display_name||member.email||"?")[0]}</span>}<span><strong>{member.display_name||member.email}</strong><small>{selected?"ร่วมเที่ยวบินนี้":"ไม่ได้เลือก"}</small></span><i>{selected&&<Check size={14}/>}</i></label>;})}</div>{members.filter(member=>selectedPassengerIds.includes(member.id)).map(member=>{const passenger=edit?.passengers.find(item=>item.user_id===member.id);return <div className="flight-passenger-editor" key={member.id}><div className="flight-passenger-editor-head"><span className="flight-passenger-name">{member.avatar_url?<Image src={member.avatar_url} alt="" width={30} height={30} unoptimized/>:<span>{(member.display_name||member.email||"?")[0]}</span>}<strong>{member.display_name||member.email}</strong></span></div><div className="flight-passenger-fields"><label><span>เลขที่นั่ง</span><input name={`seat:${member.id}`} defaultValue={passenger?.seat_number||""} placeholder="เช่น 37A"/></label><label><span>น้ำหนักกระเป๋า</span><input name={`bag:${member.id}`} defaultValue={passenger?.baggage_note||""} placeholder="เช่น 1×23 kg"/></label><label className="flight-passenger-meal-field"><span>อาหาร</span><input name={`meal:${member.id}`} defaultValue={passenger?.meal_preference||""} placeholder="เช่น Halal"/></label></div></div>;})}</div>
      {edit&&<div className="flight-document-box"><div className="flight-document-heading"><div><h3>ไฟล์ตั๋ว / Boarding pass</h3><small>เก็บเอกสารไว้เปิดดูจากหน้าเอกสารของทริป</small></div>{edit.documents.length>0&&<button type="button" onClick={onOpenDocuments}>ดูทั้งหมด</button>}</div>{edit.documents.length>0&&<div className="flight-document-existing">{edit.documents.map(document=><a key={document.id} href={`/trips/${tripId}/documents/${document.id}`}><FileText size={15}/><span>{document.title}</span></a>)}</div>}<label className={`document-file-picker flight-document-picker ${flightDocumentName?"selected":""}`}><input ref={fileRef} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={event=>setFlightDocumentName(event.target.files?.[0]?.name||"")}/><span className="document-file-picker-icon">{flightDocumentName?<Check size={22}/>:<Upload size={22}/>}</span><span><strong>{flightDocumentName||"เลือกรูปหรือไฟล์"}</strong><small>{flightDocumentName?"เลือกไฟล์แล้ว":"รองรับ JPG, PNG, WebP และ PDF"}</small></span></label><div className="field"><label htmlFor="flight-document-title">ชื่อไฟล์</label><input id="flight-document-title" name="documentTitle" placeholder="เช่น Boarding pass ขาไป"/></div><button type="button" className="secondary-btn flight-document-upload" disabled={saving||!flightDocumentName} onClick={async event=>{const form=(event.currentTarget.closest("form") as HTMLFormElement);setSaving(true);try{await uploadFile(edit,new FormData(form))}catch(reason){setError(reason instanceof Error?reason.message:"อัปโหลดไม่สำเร็จ")}finally{setSaving(false)}}}><Upload size={16}/> {saving?"กำลังอัปโหลด…":"อัปโหลดไฟล์"}</button></div>}
    </div></div><div className="modal-submit-actions flight-sheet-actions"><button className="primary-btn" disabled={saving}>{saving?"กำลังบันทึก…":"บันทึกเที่ยวบิน"}</button>{edit&&canDelete&&<button className="delete-record-btn" type="button" onClick={()=>setDeleteTarget(edit)} disabled={saving} aria-label="ลบเที่ยวบิน"><Trash2 size={18}/></button>}</div></form></div>}
    {deleteTarget&&<div className="confirm-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)setDeleteTarget(null)}}><div className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="flight-delete-title"><span className="confirm-icon"><AlertTriangle size={22}/></span><h2 id="flight-delete-title">ยืนยันการลบ</h2><p>ลบเที่ยวบิน {deleteTarget.airline_code} {deleteTarget.flight_number} ออกจากทริปนี้?</p><div className="confirm-actions"><button type="button" className="confirm-cancel" onClick={()=>setDeleteTarget(null)} disabled={saving}>ยกเลิก</button><button type="button" className="confirm-delete" onClick={()=>void remove(deleteTarget)} disabled={saving}>{saving?"กำลังลบ…":"ลบ"}</button></div></div></div>}
  </section>
}
