import { NextResponse } from "next/server";
import { getSession } from "@/src/lib/auth";
import { ensureLatestDatabaseSchema } from "@/src/lib/database-migrations";
import { query, transaction } from "@/src/lib/db";
import { flightSegmentSchema, splitFlightIdent } from "@/src/lib/flight-validation";
import { removeFlightLinkedRecords, syncFlightLinkedRecords, syncTripDayZero } from "@/src/lib/flight-linked-records";
import {
  canonicalManualFlight,
  loadFlightReferenceData,
} from "@/src/lib/flight-reference-data";
import { getTripRole, tripMemberIdsAreMembers } from "@/src/lib/trip-access";

type CurrentFlightRow={airline_code:string;airline_name:string;flight_number:string;departure_airport_code:string;departure_airport_name:string;arrival_airport_code:string;arrival_airport_name:string;departure_terminal:string|null;departure_gate:string|null;itinerary_id:string|null;ticket_cost_item_id:string|null};

export async function PATCH(request:Request,{params}:{params:Promise<{id:string;segmentId:string}>}){
  const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(session.isDemo)return NextResponse.json({error:"Demo mode is read-only",loginRequired:true},{status:403});
  const {id,segmentId}=await params;await ensureLatestDatabaseSchema();if(!await getTripRole(id,session.userId))return NextResponse.json({error:"Not found"},{status:404});
  const parsed=flightSegmentSchema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"ข้อมูลเที่ยวบินไม่ถูกต้อง"},{status:400});const input=parsed.data;
  if(!await tripMemberIdsAreMembers(id,input.passengers.map((item)=>item.userId)))return NextResponse.json({error:"ผู้โดยสารไม่ได้อยู่ในทริปนี้"},{status:400});
  try{const currentResult=await query<CurrentFlightRow>("SELECT airline_code,airline_name,flight_number,departure_airport_code,departure_airport_name,arrival_airport_code,arrival_airport_name,departure_terminal,departure_gate,itinerary_id,ticket_cost_item_id FROM trip_flight_segments WHERE id=$1 AND trip_id=$2",[segmentId,id]);const current=currentResult.rows[0];if(!current)return NextResponse.json({error:"Not found"},{status:404});const ident=splitFlightIdent(input.flightIdent);const manual=Boolean(input.manualDepartureAirportCode&&input.manualArrivalAirportCode);const canonical=manual?canonicalManualFlight(await loadFlightReferenceData(id),{airlineCode:ident.airlineCode,airlineName:input.manualAirlineName,departureAirportCode:input.manualDepartureAirportCode,departureAirportName:input.manualDepartureAirportName,arrivalAirportCode:input.manualArrivalAirportCode,arrivalAirportName:input.manualArrivalAirportName}):null;const departureCode=canonical?.departureAirportCode||current.departure_airport_code;const arrivalCode=canonical?.arrivalAirportCode||current.arrival_airport_code;const airlineName=canonical?.airlineName||current.airline_name;const departureName=canonical?.departureAirportName||current.departure_airport_name;const arrivalName=canonical?.arrivalAirportName||current.arrival_airport_name;const result=await transaction(async client=>{const adjacent=await client.query<{side:string;airport:string;moment:string}>(`(SELECT 'previous' AS side,arrival_airport_code AS airport,scheduled_arrival_at::text AS moment FROM trip_flight_segments WHERE trip_id=$1 AND id<>$2 AND journey_type=$3 AND segment_order<$4 ORDER BY segment_order DESC LIMIT 1) UNION ALL (SELECT 'next',departure_airport_code,scheduled_departure_at::text FROM trip_flight_segments WHERE trip_id=$1 AND id<>$2 AND journey_type=$3 AND segment_order>$4 ORDER BY segment_order ASC LIMIT 1)`,[id,segmentId,input.journeyType,input.segmentOrder]);for(const row of adjacent.rows){if(row.side==="previous"&&(row.airport!==departureCode||new Date(row.moment)>new Date(input.scheduledDepartureAt)))throw new Error("connection_mismatch");if(row.side==="next"&&(row.airport!==arrivalCode||new Date(input.scheduledArrivalAt)>new Date(row.moment)))throw new Error("connection_mismatch")}
    const updated=await client.query(`UPDATE trip_flight_segments SET journey_type=$3,segment_order=$4,airline_code=$5,airline_name=$6,flight_number=$7,scheduled_departure_at=$8,scheduled_arrival_at=$9,booking_reference=$10,cabin_class=$11,baggage_note=NULL,entered_departure_local=$12::timestamp,entered_arrival_local=$13::timestamp,departure_airport_code=$14,departure_airport_name=$15,arrival_airport_code=$16,arrival_airport_name=$17,provider=CASE WHEN $18 THEN 'manual' ELSE provider END,last_synced_at=CASE WHEN $18 THEN NULL ELSE last_synced_at END,updated_at=now() WHERE id=$1 AND trip_id=$2 RETURNING *`,[segmentId,id,input.journeyType,input.segmentOrder,ident.airlineCode,airlineName,ident.flightNumber,input.scheduledDepartureAt,input.scheduledArrivalAt,input.bookingReference||null,input.cabinClass||null,input.enteredDepartureLocal,input.enteredArrivalLocal,departureCode,departureName,arrivalCode,arrivalName,manual]);await client.query("DELETE FROM trip_flight_passengers WHERE segment_id=$1",[segmentId]);for(const passenger of input.passengers)await client.query(`INSERT INTO trip_flight_passengers (segment_id,user_id,seat_number,meal_preference,carry_on_baggage,checked_baggage) VALUES ($1,$2,$3,$4,$5,$6)`,[segmentId,passenger.userId,passenger.seatNumber||null,passenger.mealPreference||null,passenger.carryOnBaggage||null,passenger.checkedBaggage||null]);await syncFlightLinkedRecords(client,{tripId:id,segmentId,flightLabel:`${ident.airlineCode}${ident.flightNumber}`,airlineName,departureAirportCode:departureCode,departureAirportName:departureName,arrivalAirportCode:arrivalCode,arrivalAirportName:arrivalName,scheduledDepartureAt:input.scheduledDepartureAt,enteredDepartureLocal:input.enteredDepartureLocal,departureTerminal:manual?null:current.departure_terminal,departureGate:manual?null:current.departure_gate,ticketPrice:input.ticketPrice,ticketCurrency:input.ticketCurrency,ticketExchangeRate:input.ticketExchangeRate,ticketRateDate:input.ticketRateDate,passengerIds:input.passengers.map(passenger=>passenger.userId),itineraryId:current.itinerary_id,ticketCostItemId:current.ticket_cost_item_id});await syncTripDayZero(client,id);return updated.rows[0]});return NextResponse.json(result)}catch(error){const code=error instanceof Error?error.message:"";return NextResponse.json({error:code==="connection_mismatch"?"ช่วงต่อเครื่องต้องใช้สนามบินเดียวกันและเวลาไม่ย้อนกัน":"แก้ไขเที่ยวบินไม่สำเร็จ"},{status:400})}
}

export async function DELETE(_:Request,{params}:{params:Promise<{id:string;segmentId:string}>}){
  const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorized"},{status:401});if(session.isDemo)return NextResponse.json({error:"Demo mode is read-only",loginRequired:true},{status:403});const {id,segmentId}=await params;await ensureLatestDatabaseSchema();const role=await getTripRole(id,session.userId);if(role!=="owner"&&role!=="admin")return NextResponse.json({error:"สิทธิ์ View ไม่มีสิทธิลบเที่ยวบิน"},{status:403});const removed=await transaction(async client=>{const current=await client.query<{itinerary_id:string|null;ticket_cost_item_id:string|null}>("SELECT itinerary_id,ticket_cost_item_id FROM trip_flight_segments WHERE id=$1 AND trip_id=$2",[segmentId,id]);if(!current.rows[0])return false;await removeFlightLinkedRecords(client,id,current.rows[0].itinerary_id,current.rows[0].ticket_cost_item_id);await client.query("DELETE FROM trip_flight_segments WHERE id=$1 AND trip_id=$2",[segmentId,id]);await syncTripDayZero(client,id);return true});return removed?NextResponse.json({ok:true}):NextResponse.json({error:"Not found"},{status:404});
}
